# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Z:\Qt Polonator\polonatorprocessor.ui'
#
# Created: Tue Nov 02 17:01:43 2010
#      by: PyQt4 UI code generator 4.5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1339, 800)
        font = QtGui.QFont()
        font.setFamily("Arial")
        MainWindow.setFont(font)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 20, 1301, 731))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtGui.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.polonator_textarea = QtGui.QTextEdit(self.tab_1)
        self.polonator_textarea.setGeometry(QtCore.QRect(550, 10, 731, 691))
        self.polonator_textarea.setObjectName("polonator_textarea")
        self.frame_12 = QtGui.QFrame(self.tab_1)
        self.frame_12.setGeometry(QtCore.QRect(20, 10, 521, 561))
        self.frame_12.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.frame_9 = QtGui.QFrame(self.frame_12)
        self.frame_9.setGeometry(QtCore.QRect(10, 120, 201, 81))
        self.frame_9.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.polonator_initialize = QtGui.QPushButton(self.frame_9)
        self.polonator_initialize.setGeometry(QtCore.QRect(30, 10, 131, 23))
        self.polonator_initialize.setObjectName("polonator_initialize")
        self.polonator_process = QtGui.QPushButton(self.frame_9)
        self.polonator_process.setGeometry(QtCore.QRect(30, 40, 131, 23))
        self.polonator_process.setObjectName("polonator_process")
        self.polonator_initializewidget = QtGui.QWidget(self.frame_12)
        self.polonator_initializewidget.setGeometry(QtCore.QRect(20, 420, 491, 101))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.NoRole, brush)
        self.polonator_initializewidget.setPalette(palette)
        self.polonator_initializewidget.setObjectName("polonator_initializewidget")
        self.polonator_initializestatus = QtGui.QLabel(self.polonator_initializewidget)
        self.polonator_initializestatus.setGeometry(QtCore.QRect(30, 20, 111, 21))
        self.polonator_initializestatus.setFrameShape(QtGui.QFrame.Box)
        self.polonator_initializestatus.setObjectName("polonator_initializestatus")
        self.label_5 = QtGui.QLabel(self.polonator_initializewidget)
        self.label_5.setGeometry(QtCore.QRect(10, 0, 121, 16))
        self.label_5.setObjectName("label_5")
        self.polonator_initializepath = QtGui.QLabel(self.polonator_initializewidget)
        self.polonator_initializepath.setGeometry(QtCore.QRect(30, 50, 451, 41))
        self.polonator_initializepath.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.polonator_initializepath.setObjectName("polonator_initializepath")
        self.label_2 = QtGui.QLabel(self.frame_12)
        self.label_2.setGeometry(QtCore.QRect(10, 270, 141, 31))
        self.label_2.setObjectName("label_2")
        self.polonator_processingframe = QtGui.QFrame(self.frame_12)
        self.polonator_processingframe.setGeometry(QtCore.QRect(20, 290, 491, 111))
        self.polonator_processingframe.setFrameShape(QtGui.QFrame.NoFrame)
        self.polonator_processingframe.setFrameShadow(QtGui.QFrame.Raised)
        self.polonator_processingframe.setObjectName("polonator_processingframe")
        self.polonator_processorstatus = QtGui.QLabel(self.polonator_processingframe)
        self.polonator_processorstatus.setGeometry(QtCore.QRect(30, 30, 111, 21))
        self.polonator_processorstatus.setFrameShape(QtGui.QFrame.Box)
        self.polonator_processorstatus.setObjectName("polonator_processorstatus")
        self.label_3 = QtGui.QLabel(self.polonator_processingframe)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 121, 16))
        self.label_3.setObjectName("label_3")
        self.polonator_processorpath = QtGui.QLabel(self.polonator_processingframe)
        self.polonator_processorpath.setGeometry(QtCore.QRect(30, 60, 451, 41))
        self.polonator_processorpath.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.polonator_processorpath.setObjectName("polonator_processorpath")
        self.polonator_kill = QtGui.QPushButton(self.frame_12)
        self.polonator_kill.setGeometry(QtCore.QRect(10, 530, 241, 23))
        self.polonator_kill.setObjectName("polonator_kill")
        self.label = QtGui.QLabel(self.frame_12)
        self.label.setGeometry(QtCore.QRect(10, 20, 121, 16))
        self.label.setObjectName("label")
        self.polonator_experiment = QtGui.QLabel(self.frame_12)
        self.polonator_experiment.setGeometry(QtCore.QRect(20, 40, 481, 71))
        self.polonator_experiment.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.polonator_experiment.setWordWrap(True)
        self.polonator_experiment.setObjectName("polonator_experiment")
        self.pushButton = QtGui.QPushButton(self.tab_1)
        self.pushButton.setGeometry(QtCore.QRect(50, 580, 111, 23))
        self.pushButton.setObjectName("pushButton")
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.imageJPanel2 = QtGui.QGraphicsView(self.tab_2)
        self.imageJPanel2.setGeometry(QtCore.QRect(980, 20, 300, 300))
        self.imageJPanel2.setObjectName("imageJPanel2")
        self.frame_13 = QtGui.QFrame(self.tab_2)
        self.frame_13.setGeometry(QtCore.QRect(20, 30, 591, 191))
        self.frame_13.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.label_8 = QtGui.QLabel(self.frame_13)
        self.label_8.setGeometry(QtCore.QRect(210, 0, 91, 16))
        self.label_8.setObjectName("label_8")
        self.startQC = QtGui.QPushButton(self.frame_13)
        self.startQC.setGeometry(QtCore.QRect(210, 160, 171, 23))
        self.startQC.setObjectName("startQC")
        self.cycleListComplete = QtGui.QListWidget(self.frame_13)
        self.cycleListComplete.setGeometry(QtCore.QRect(10, 20, 171, 131))
        self.cycleListComplete.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.cycleListComplete.setObjectName("cycleListComplete")
        self.cycleListInProgress = QtGui.QListWidget(self.frame_13)
        self.cycleListInProgress.setGeometry(QtCore.QRect(410, 20, 171, 131))
        self.cycleListInProgress.setObjectName("cycleListInProgress")
        self.label_9 = QtGui.QLabel(self.frame_13)
        self.label_9.setGeometry(QtCore.QRect(410, 0, 91, 16))
        self.label_9.setObjectName("label_9")
        self.cycleListPending = QtGui.QListWidget(self.frame_13)
        self.cycleListPending.setGeometry(QtCore.QRect(210, 20, 171, 131))
        self.cycleListPending.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.cycleListPending.setObjectName("cycleListPending")
        QtGui.QListWidgetItem(self.cycleListPending)
        QtGui.QListWidgetItem(self.cycleListPending)
        QtGui.QListWidgetItem(self.cycleListPending)
        QtGui.QListWidgetItem(self.cycleListPending)
        QtGui.QListWidgetItem(self.cycleListPending)
        self.label_7 = QtGui.QLabel(self.frame_13)
        self.label_7.setGeometry(QtCore.QRect(10, 0, 91, 16))
        self.label_7.setObjectName("label_7")
        self.plainTextEdit = QtGui.QPlainTextEdit(self.tab_2)
        self.plainTextEdit.setGeometry(QtCore.QRect(130, 280, 411, 301))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.pushButton_4 = QtGui.QPushButton(self.tab_2)
        self.pushButton_4.setGeometry(QtCore.QRect(80, 230, 201, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.imageJPanel1 = QtGui.QGraphicsView(self.tab_2)
        self.imageJPanel1.setGeometry(QtCore.QRect(630, 20, 300, 300))
        self.imageJPanel1.setObjectName("imageJPanel1")
        self.alignXImageJPanel = QtGui.QGraphicsView(self.tab_2)
        self.alignXImageJPanel.setGeometry(QtCore.QRect(630, 370, 300, 300))
        self.alignXImageJPanel.setObjectName("alignXImageJPanel")
        self.alignYImageJPanel = QtGui.QGraphicsView(self.tab_2)
        self.alignYImageJPanel.setGeometry(QtCore.QRect(980, 370, 300, 300))
        self.alignYImageJPanel.setObjectName("alignYImageJPanel")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.frame = QtGui.QFrame(self.tab_4)
        self.frame.setGeometry(QtCore.QRect(30, 30, 211, 191))
        self.frame.setFrameShape(QtGui.QFrame.Box)
        self.frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.label_10 = QtGui.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(20, 20, 46, 21))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtGui.QLabel(self.frame)
        self.label_11.setGeometry(QtCore.QRect(20, 60, 46, 21))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtGui.QLabel(self.frame)
        self.label_12.setGeometry(QtCore.QRect(20, 100, 46, 21))
        self.label_12.setObjectName("label_12")
        self.objectPosition = QtGui.QSpinBox(self.frame)
        self.objectPosition.setGeometry(QtCore.QRect(120, 100, 71, 22))
        self.objectPosition.setObjectName("objectPosition")
        self.objectFC = QtGui.QComboBox(self.frame)
        self.objectFC.setGeometry(QtCore.QRect(120, 22, 69, 20))
        self.objectFC.setObjectName("objectFC")
        self.objectFC.addItem(QtCore.QString())
        self.objectFC.addItem(QtCore.QString())
        self.objectLane = QtGui.QComboBox(self.frame)
        self.objectLane.setGeometry(QtCore.QRect(120, 60, 69, 22))
        self.objectLane.setObjectName("objectLane")
        self.objectLane.addItem(QtCore.QString())
        self.objectLane.addItem(QtCore.QString())
        self.objectLane.addItem(QtCore.QString())
        self.objectLane.addItem(QtCore.QString())
        self.objectLane.addItem(QtCore.QString())
        self.objectLane.addItem(QtCore.QString())
        self.objectLane.addItem(QtCore.QString())
        self.objectLane.addItem(QtCore.QString())
        self.objectDisplay = QtGui.QPushButton(self.frame)
        self.objectDisplay.setGeometry(QtCore.QRect(20, 140, 171, 23))
        self.objectDisplay.setObjectName("objectDisplay")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.frame_2 = QtGui.QFrame(self.tab_5)
        self.frame_2.setGeometry(QtCore.QRect(20, 20, 281, 281))
        self.frame_2.setFrameShape(QtGui.QFrame.Box)
        self.frame_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_2.setObjectName("frame_2")
        self.rawCycleList = QtGui.QListWidget(self.frame_2)
        self.rawCycleList.setGeometry(QtCore.QRect(10, 10, 111, 151))
        self.rawCycleList.setObjectName("rawCycleList")
        QtGui.QListWidgetItem(self.rawCycleList)
        QtGui.QListWidgetItem(self.rawCycleList)
        QtGui.QListWidgetItem(self.rawCycleList)
        QtGui.QListWidgetItem(self.rawCycleList)
        QtGui.QListWidgetItem(self.rawCycleList)
        self.label_4 = QtGui.QLabel(self.frame_2)
        self.label_4.setEnabled(False)
        self.label_4.setGeometry(QtCore.QRect(130, 10, 51, 16))
        self.label_4.setObjectName("label_4")
        self.rawFlowcell = QtGui.QComboBox(self.frame_2)
        self.rawFlowcell.setEnabled(False)
        self.rawFlowcell.setGeometry(QtCore.QRect(130, 30, 51, 22))
        self.rawFlowcell.setObjectName("rawFlowcell")
        self.rawFlowcell.addItem(QtCore.QString())
        self.rawFlowcell.addItem(QtCore.QString())
        self.rawLane = QtGui.QComboBox(self.frame_2)
        self.rawLane.setGeometry(QtCore.QRect(130, 80, 51, 22))
        self.rawLane.setObjectName("rawLane")
        self.rawLane.addItem(QtCore.QString())
        self.rawLane.addItem(QtCore.QString())
        self.rawLane.addItem(QtCore.QString())
        self.rawLane.addItem(QtCore.QString())
        self.rawLane.addItem(QtCore.QString())
        self.rawLane.addItem(QtCore.QString())
        self.rawLane.addItem(QtCore.QString())
        self.rawLane.addItem(QtCore.QString())
        self.rawRed = QtGui.QComboBox(self.frame_2)
        self.rawRed.setGeometry(QtCore.QRect(30, 190, 51, 22))
        self.rawRed.setObjectName("rawRed")
        self.rawRed.addItem(QtCore.QString())
        self.rawRed.addItem(QtCore.QString())
        self.rawRed.addItem(QtCore.QString())
        self.rawRed.addItem(QtCore.QString())
        self.rawRed.addItem(QtCore.QString())
        self.rawGreen = QtGui.QComboBox(self.frame_2)
        self.rawGreen.setGeometry(QtCore.QRect(120, 190, 51, 22))
        self.rawGreen.setObjectName("rawGreen")
        self.rawGreen.addItem(QtCore.QString())
        self.rawGreen.addItem(QtCore.QString())
        self.rawGreen.addItem(QtCore.QString())
        self.rawGreen.addItem(QtCore.QString())
        self.rawGreen.addItem(QtCore.QString())
        self.rawBlue = QtGui.QComboBox(self.frame_2)
        self.rawBlue.setGeometry(QtCore.QRect(210, 190, 51, 22))
        self.rawBlue.setObjectName("rawBlue")
        self.rawBlue.addItem(QtCore.QString())
        self.rawBlue.addItem(QtCore.QString())
        self.rawBlue.addItem(QtCore.QString())
        self.rawBlue.addItem(QtCore.QString())
        self.rawBlue.addItem(QtCore.QString())
        self.label_6 = QtGui.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(130, 60, 46, 16))
        self.label_6.setObjectName("label_6")
        self.label_13 = QtGui.QLabel(self.frame_2)
        self.label_13.setGeometry(QtCore.QRect(130, 110, 46, 16))
        self.label_13.setObjectName("label_13")
        self.rawImage = QtGui.QSpinBox(self.frame_2)
        self.rawImage.setGeometry(QtCore.QRect(130, 130, 51, 22))
        self.rawImage.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.rawImage.setMaximum(9999)
        self.rawImage.setObjectName("rawImage")
        self.label_14 = QtGui.QLabel(self.frame_2)
        self.label_14.setGeometry(QtCore.QRect(30, 170, 46, 14))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtGui.QLabel(self.frame_2)
        self.label_15.setGeometry(QtCore.QRect(120, 170, 46, 14))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtGui.QLabel(self.frame_2)
        self.label_16.setGeometry(QtCore.QRect(210, 170, 46, 14))
        self.label_16.setObjectName("label_16")
        self.rawDisplay = QtGui.QPushButton(self.frame_2)
        self.rawDisplay.setGeometry(QtCore.QRect(30, 230, 231, 23))
        self.rawDisplay.setObjectName("rawDisplay")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.histogramOutputWindow = QtGui.QPlainTextEdit(self.tab_6)
        self.histogramOutputWindow.setGeometry(QtCore.QRect(360, 10, 931, 691))
        self.histogramOutputWindow.setObjectName("histogramOutputWindow")
        self.frame_14 = QtGui.QFrame(self.tab_6)
        self.frame_14.setGeometry(QtCore.QRect(10, 10, 321, 691))
        self.frame_14.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.histogramFileList = QtGui.QListWidget(self.frame_14)
        self.histogramFileList.setGeometry(QtCore.QRect(10, 10, 121, 681))
        self.histogramFileList.setObjectName("histogramFileList")
        QtGui.QListWidgetItem(self.histogramFileList)
        QtGui.QListWidgetItem(self.histogramFileList)
        QtGui.QListWidgetItem(self.histogramFileList)
        QtGui.QListWidgetItem(self.histogramFileList)
        QtGui.QListWidgetItem(self.histogramFileList)
        self.frame_15 = QtGui.QFrame(self.frame_14)
        self.frame_15.setGeometry(QtCore.QRect(140, 10, 181, 161))
        self.frame_15.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.label_17 = QtGui.QLabel(self.frame_15)
        self.label_17.setGeometry(QtCore.QRect(10, 0, 46, 21))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtGui.QLabel(self.frame_15)
        self.label_18.setGeometry(QtCore.QRect(10, 40, 46, 21))
        self.label_18.setObjectName("label_18")
        self.histogramThreshold = QtGui.QLineEdit(self.frame_15)
        self.histogramThreshold.setGeometry(QtCore.QRect(10, 100, 81, 20))
        self.histogramThreshold.setObjectName("histogramThreshold")
        self.histogramFlowcell = QtGui.QLineEdit(self.frame_15)
        self.histogramFlowcell.setGeometry(QtCore.QRect(10, 20, 81, 20))
        self.histogramFlowcell.setObjectName("histogramFlowcell")
        self.histogramLane = QtGui.QLineEdit(self.frame_15)
        self.histogramLane.setGeometry(QtCore.QRect(10, 60, 81, 20))
        self.histogramLane.setObjectName("histogramLane")
        self.histogramDrawHistogram = QtGui.QPushButton(self.frame_15)
        self.histogramDrawHistogram.setGeometry(QtCore.QRect(10, 130, 161, 23))
        self.histogramDrawHistogram.setObjectName("histogramDrawHistogram")
        self.label_19 = QtGui.QLabel(self.frame_15)
        self.label_19.setGeometry(QtCore.QRect(10, 80, 46, 21))
        self.label_19.setObjectName("label_19")
        self.frame_16 = QtGui.QFrame(self.frame_14)
        self.frame_16.setGeometry(QtCore.QRect(140, 170, 181, 521))
        self.frame_16.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.histogramCutoff0_2 = QtGui.QLineEdit(self.frame_16)
        self.histogramCutoff0_2.setGeometry(QtCore.QRect(70, 90, 81, 20))
        self.histogramCutoff0_2.setObjectName("histogramCutoff0_2")
        self.histogramCutoff0_3 = QtGui.QLineEdit(self.frame_16)
        self.histogramCutoff0_3.setGeometry(QtCore.QRect(70, 110, 81, 20))
        self.histogramCutoff0_3.setObjectName("histogramCutoff0_3")
        self.label_32 = QtGui.QLabel(self.frame_16)
        self.label_32.setGeometry(QtCore.QRect(20, 50, 46, 14))
        self.label_32.setObjectName("label_32")
        self.histogramCutoff1_7 = QtGui.QLineEdit(self.frame_16)
        self.histogramCutoff1_7.setGeometry(QtCore.QRect(70, 370, 81, 20))
        self.histogramCutoff1_7.setObjectName("histogramCutoff1_7")
        self.label_25 = QtGui.QLabel(self.frame_16)
        self.label_25.setGeometry(QtCore.QRect(20, 150, 46, 14))
        self.label_25.setObjectName("label_25")
        self.histogramCutoff0_1 = QtGui.QLineEdit(self.frame_16)
        self.histogramCutoff0_1.setGeometry(QtCore.QRect(70, 70, 81, 20))
        self.histogramCutoff0_1.setObjectName("histogramCutoff0_1")
        self.label_23 = QtGui.QLabel(self.frame_16)
        self.label_23.setGeometry(QtCore.QRect(20, 110, 46, 14))
        self.label_23.setObjectName("label_23")
        self.histogramCutoff0_7 = QtGui.QLineEdit(self.frame_16)
        self.histogramCutoff0_7.setGeometry(QtCore.QRect(70, 190, 81, 20))
        self.histogramCutoff0_7.setObjectName("histogramCutoff0_7")
        self.label_68 = QtGui.QLabel(self.frame_16)
        self.label_68.setGeometry(QtCore.QRect(20, 230, 46, 14))
        self.label_68.setObjectName("label_68")
        self.histogramCutoff0_0 = QtGui.QLineEdit(self.frame_16)
        self.histogramCutoff0_0.setGeometry(QtCore.QRect(70, 50, 81, 20))
        self.histogramCutoff0_0.setObjectName("histogramCutoff0_0")
        self.histogramCutoff1_6 = QtGui.QLineEdit(self.frame_16)
        self.histogramCutoff1_6.setGeometry(QtCore.QRect(70, 350, 81, 20))
        self.histogramCutoff1_6.setObjectName("histogramCutoff1_6")
        self.histogramCutoff1_4 = QtGui.QLineEdit(self.frame_16)
        self.histogramCutoff1_4.setGeometry(QtCore.QRect(70, 310, 81, 20))
        self.histogramCutoff1_4.setObjectName("histogramCutoff1_4")
        self.histogramCutoff1_5 = QtGui.QLineEdit(self.frame_16)
        self.histogramCutoff1_5.setGeometry(QtCore.QRect(70, 330, 81, 20))
        self.histogramCutoff1_5.setObjectName("histogramCutoff1_5")
        self.label_24 = QtGui.QLabel(self.frame_16)
        self.label_24.setGeometry(QtCore.QRect(20, 130, 46, 14))
        self.label_24.setObjectName("label_24")
        self.histogramCutoff1_1 = QtGui.QLineEdit(self.frame_16)
        self.histogramCutoff1_1.setGeometry(QtCore.QRect(70, 250, 81, 20))
        self.histogramCutoff1_1.setObjectName("histogramCutoff1_1")
        self.histogramCutoff1_2 = QtGui.QLineEdit(self.frame_16)
        self.histogramCutoff1_2.setGeometry(QtCore.QRect(70, 270, 81, 20))
        self.histogramCutoff1_2.setObjectName("histogramCutoff1_2")
        self.histogramCutoff0_4 = QtGui.QLineEdit(self.frame_16)
        self.histogramCutoff0_4.setGeometry(QtCore.QRect(70, 130, 81, 20))
        self.histogramCutoff0_4.setObjectName("histogramCutoff0_4")
        self.label_70 = QtGui.QLabel(self.frame_16)
        self.label_70.setGeometry(QtCore.QRect(20, 270, 46, 14))
        self.label_70.setObjectName("label_70")
        self.label_67 = QtGui.QLabel(self.frame_16)
        self.label_67.setGeometry(QtCore.QRect(10, 210, 46, 20))
        self.label_67.setObjectName("label_67")
        self.label_20 = QtGui.QLabel(self.frame_16)
        self.label_20.setGeometry(QtCore.QRect(10, 10, 161, 20))
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.label_73 = QtGui.QLabel(self.frame_16)
        self.label_73.setGeometry(QtCore.QRect(20, 330, 46, 14))
        self.label_73.setObjectName("label_73")
        self.histogramCutoff1_3 = QtGui.QLineEdit(self.frame_16)
        self.histogramCutoff1_3.setGeometry(QtCore.QRect(70, 290, 81, 20))
        self.histogramCutoff1_3.setObjectName("histogramCutoff1_3")
        self.label_26 = QtGui.QLabel(self.frame_16)
        self.label_26.setGeometry(QtCore.QRect(20, 170, 46, 14))
        self.label_26.setObjectName("label_26")
        self.label_71 = QtGui.QLabel(self.frame_16)
        self.label_71.setGeometry(QtCore.QRect(20, 290, 46, 14))
        self.label_71.setObjectName("label_71")
        self.label_72 = QtGui.QLabel(self.frame_16)
        self.label_72.setGeometry(QtCore.QRect(20, 310, 46, 14))
        self.label_72.setObjectName("label_72")
        self.label_22 = QtGui.QLabel(self.frame_16)
        self.label_22.setGeometry(QtCore.QRect(20, 90, 46, 14))
        self.label_22.setObjectName("label_22")
        self.label_21 = QtGui.QLabel(self.frame_16)
        self.label_21.setGeometry(QtCore.QRect(10, 30, 46, 20))
        self.label_21.setObjectName("label_21")
        self.histogramCutoff0_6 = QtGui.QLineEdit(self.frame_16)
        self.histogramCutoff0_6.setGeometry(QtCore.QRect(70, 170, 81, 20))
        self.histogramCutoff0_6.setObjectName("histogramCutoff0_6")
        self.label_75 = QtGui.QLabel(self.frame_16)
        self.label_75.setGeometry(QtCore.QRect(20, 370, 46, 14))
        self.label_75.setObjectName("label_75")
        self.label_74 = QtGui.QLabel(self.frame_16)
        self.label_74.setGeometry(QtCore.QRect(20, 344, 46, 20))
        self.label_74.setObjectName("label_74")
        self.histogramCutoff1_0 = QtGui.QLineEdit(self.frame_16)
        self.histogramCutoff1_0.setGeometry(QtCore.QRect(70, 230, 81, 20))
        self.histogramCutoff1_0.setObjectName("histogramCutoff1_0")
        self.label_33 = QtGui.QLabel(self.frame_16)
        self.label_33.setGeometry(QtCore.QRect(20, 64, 46, 20))
        self.label_33.setObjectName("label_33")
        self.label_69 = QtGui.QLabel(self.frame_16)
        self.label_69.setGeometry(QtCore.QRect(20, 250, 46, 14))
        self.label_69.setObjectName("label_69")
        self.label_27 = QtGui.QLabel(self.frame_16)
        self.label_27.setGeometry(QtCore.QRect(20, 190, 46, 14))
        self.label_27.setObjectName("label_27")
        self.histogramCutoff0_5 = QtGui.QLineEdit(self.frame_16)
        self.histogramCutoff0_5.setGeometry(QtCore.QRect(70, 150, 81, 20))
        self.histogramCutoff0_5.setObjectName("histogramCutoff0_5")
        self.histogramSingleButton = QtGui.QRadioButton(self.frame_16)
        self.histogramSingleButton.setGeometry(QtCore.QRect(30, 490, 60, 18))
        self.histogramSingleButton.setObjectName("histogramSingleButton")
        self.histogramGenerateData = QtGui.QPushButton(self.frame_16)
        self.histogramGenerateData.setGeometry(QtCore.QRect(10, 460, 161, 23))
        self.histogramGenerateData.setObjectName("histogramGenerateData")
        self.histogramSetCutoffs = QtGui.QPushButton(self.frame_16)
        self.histogramSetCutoffs.setGeometry(QtCore.QRect(10, 430, 161, 23))
        self.histogramSetCutoffs.setObjectName("histogramSetCutoffs")
        self.histogramCycleButton = QtGui.QRadioButton(self.frame_16)
        self.histogramCycleButton.setGeometry(QtCore.QRect(100, 490, 60, 18))
        self.histogramCycleButton.setChecked(True)
        self.histogramCycleButton.setObjectName("histogramCycleButton")
        self.histogramLoadCutoffs = QtGui.QPushButton(self.frame_16)
        self.histogramLoadCutoffs.setGeometry(QtCore.QRect(10, 400, 161, 23))
        self.histogramLoadCutoffs.setObjectName("histogramLoadCutoffs")
        self.pushButton_3 = QtGui.QPushButton(self.tab_6)
        self.pushButton_3.setGeometry(QtCore.QRect(390, 80, 221, 41))
        self.pushButton_3.setObjectName("pushButton_3")
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.frame_5 = QtGui.QFrame(self.tab_7)
        self.frame_5.setGeometry(QtCore.QRect(10, 10, 461, 371))
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_28 = QtGui.QLabel(self.frame_5)
        self.label_28.setGeometry(QtCore.QRect(10, 10, 101, 16))
        self.label_28.setObjectName("label_28")
        self.basecallerUpButton = QtGui.QPushButton(self.frame_5)
        self.basecallerUpButton.setGeometry(QtCore.QRect(400, 90, 41, 23))
        self.basecallerUpButton.setObjectName("basecallerUpButton")
        self.label_29 = QtGui.QLabel(self.frame_5)
        self.label_29.setGeometry(QtCore.QRect(260, 10, 101, 16))
        self.label_29.setObjectName("label_29")
        self.basecallerReadOrderList = QtGui.QListWidget(self.frame_5)
        self.basecallerReadOrderList.setGeometry(QtCore.QRect(260, 30, 121, 321))
        self.basecallerReadOrderList.setObjectName("basecallerReadOrderList")
        QtGui.QListWidgetItem(self.basecallerReadOrderList)
        QtGui.QListWidgetItem(self.basecallerReadOrderList)
        QtGui.QListWidgetItem(self.basecallerReadOrderList)
        QtGui.QListWidgetItem(self.basecallerReadOrderList)
        self.basecallerDownButton = QtGui.QPushButton(self.frame_5)
        self.basecallerDownButton.setGeometry(QtCore.QRect(400, 120, 41, 23))
        self.basecallerDownButton.setObjectName("basecallerDownButton")
        self.basecallerAvailCyclesList = QtGui.QListWidget(self.frame_5)
        self.basecallerAvailCyclesList.setGeometry(QtCore.QRect(10, 30, 121, 321))
        self.basecallerAvailCyclesList.setObjectName("basecallerAvailCyclesList")
        QtGui.QListWidgetItem(self.basecallerAvailCyclesList)
        QtGui.QListWidgetItem(self.basecallerAvailCyclesList)
        QtGui.QListWidgetItem(self.basecallerAvailCyclesList)
        QtGui.QListWidgetItem(self.basecallerAvailCyclesList)
        QtGui.QListWidgetItem(self.basecallerAvailCyclesList)
        self.frame_17 = QtGui.QFrame(self.frame_5)
        self.frame_17.setGeometry(QtCore.QRect(140, 60, 111, 111))
        self.frame_17.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.basecallerAddAllButton = QtGui.QPushButton(self.frame_17)
        self.basecallerAddAllButton.setGeometry(QtCore.QRect(10, 80, 91, 23))
        self.basecallerAddAllButton.setObjectName("basecallerAddAllButton")
        self.basecallerRemoveButton = QtGui.QPushButton(self.frame_17)
        self.basecallerRemoveButton.setGeometry(QtCore.QRect(10, 50, 91, 23))
        self.basecallerRemoveButton.setObjectName("basecallerRemoveButton")
        self.basecallerAddButton = QtGui.QPushButton(self.frame_17)
        self.basecallerAddButton.setGeometry(QtCore.QRect(10, 10, 91, 31))
        self.basecallerAddButton.setObjectName("basecallerAddButton")
        self.pushButton_2 = QtGui.QPushButton(self.frame_5)
        self.pushButton_2.setGeometry(QtCore.QRect(100, 340, 191, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.frame_6 = QtGui.QFrame(self.tab_7)
        self.frame_6.setGeometry(QtCore.QRect(10, 390, 461, 301))
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.basecallerRunBasecallerButton = QtGui.QPushButton(self.frame_6)
        self.basecallerRunBasecallerButton.setGeometry(QtCore.QRect(10, 270, 371, 23))
        self.basecallerRunBasecallerButton.setObjectName("basecallerRunBasecallerButton")
        self.jSlider2 = QtGui.QSlider(self.frame_6)
        self.jSlider2.setGeometry(QtCore.QRect(10, 210, 371, 20))
        self.jSlider2.setMaximum(20)
        self.jSlider2.setPageStep(5)
        self.jSlider2.setProperty("value", QtCore.QVariant(5))
        self.jSlider2.setSliderPosition(5)
        self.jSlider2.setOrientation(QtCore.Qt.Horizontal)
        self.jSlider2.setTickPosition(QtGui.QSlider.TicksBelow)
        self.jSlider2.setTickInterval(1)
        self.jSlider2.setObjectName("jSlider2")
        self.basecallerPercentToKeepLabel = QtGui.QLabel(self.frame_6)
        self.basecallerPercentToKeepLabel.setGeometry(QtCore.QRect(180, 80, 31, 16))
        self.basecallerPercentToKeepLabel.setFrameShape(QtGui.QFrame.Box)
        self.basecallerPercentToKeepLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.basecallerPercentToKeepLabel.setObjectName("basecallerPercentToKeepLabel")
        self.label_30 = QtGui.QLabel(self.frame_6)
        self.label_30.setGeometry(QtCore.QRect(30, 10, 111, 16))
        self.label_30.setObjectName("label_30")
        self.jSlider1 = QtGui.QSlider(self.frame_6)
        self.jSlider1.setGeometry(QtCore.QRect(10, 110, 371, 20))
        self.jSlider1.setMaximum(100)
        self.jSlider1.setPageStep(10)
        self.jSlider1.setSliderPosition(50)
        self.jSlider1.setOrientation(QtCore.Qt.Horizontal)
        self.jSlider1.setTickPosition(QtGui.QSlider.TicksBelow)
        self.jSlider1.setTickInterval(1)
        self.jSlider1.setObjectName("jSlider1")
        self.basecallerPercentBGSubtractLabel = QtGui.QLabel(self.frame_6)
        self.basecallerPercentBGSubtractLabel.setGeometry(QtCore.QRect(180, 180, 21, 16))
        self.basecallerPercentBGSubtractLabel.setFrameShape(QtGui.QFrame.Box)
        self.basecallerPercentBGSubtractLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.basecallerPercentBGSubtractLabel.setObjectName("basecallerPercentBGSubtractLabel")
        self.basecallerReadfileFN = QtGui.QLineEdit(self.frame_6)
        self.basecallerReadfileFN.setGeometry(QtCore.QRect(50, 40, 113, 20))
        self.basecallerReadfileFN.setObjectName("basecallerReadfileFN")
        self.label_31 = QtGui.QLabel(self.frame_6)
        self.label_31.setGeometry(QtCore.QRect(30, 80, 137, 14))
        self.label_31.setObjectName("label_31")
        self.label_76 = QtGui.QLabel(self.frame_6)
        self.label_76.setGeometry(QtCore.QRect(30, 180, 144, 16))
        self.label_76.setObjectName("label_76")
        self.frame_7 = QtGui.QFrame(self.tab_7)
        self.frame_7.setGeometry(QtCore.QRect(480, 10, 801, 681))
        self.frame_7.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.basecallerOutputWindow = QtGui.QPlainTextEdit(self.frame_7)
        self.basecallerOutputWindow.setGeometry(QtCore.QRect(10, 10, 791, 671))
        self.basecallerOutputWindow.setObjectName("basecallerOutputWindow")
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_8 = QtGui.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.frame_8 = QtGui.QFrame(self.tab_8)
        self.frame_8.setGeometry(QtCore.QRect(20, 20, 471, 441))
        self.frame_8.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.label_77 = QtGui.QLabel(self.frame_8)
        self.label_77.setGeometry(QtCore.QRect(30, 20, 231, 16))
        self.label_77.setObjectName("label_77")
        self.label_78 = QtGui.QLabel(self.frame_8)
        self.label_78.setGeometry(QtCore.QRect(30, 60, 231, 16))
        self.label_78.setObjectName("label_78")
        self.label_79 = QtGui.QLabel(self.frame_8)
        self.label_79.setGeometry(QtCore.QRect(30, 100, 231, 16))
        self.label_79.setObjectName("label_79")
        self.label_80 = QtGui.QLabel(self.frame_8)
        self.label_80.setGeometry(QtCore.QRect(30, 140, 321, 16))
        self.label_80.setObjectName("label_80")
        self.tabWidget.addTab(self.tab_8, "")
        self.statusLabel = QtGui.QLabel(self.centralwidget)
        self.statusLabel.setGeometry(QtCore.QRect(20, 760, 1301, 16))
        self.statusLabel.setFrameShape(QtGui.QFrame.Box)
        self.statusLabel.setObjectName("statusLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.histogramFileList.setCurrentRow(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabWidget, self.polonator_initialize)
        MainWindow.setTabOrder(self.polonator_initialize, self.polonator_process)
        MainWindow.setTabOrder(self.polonator_process, self.polonator_kill)
        MainWindow.setTabOrder(self.polonator_kill, self.pushButton)
        MainWindow.setTabOrder(self.pushButton, self.polonator_textarea)
        MainWindow.setTabOrder(self.polonator_textarea, self.cycleListComplete)
        MainWindow.setTabOrder(self.cycleListComplete, self.cycleListPending)
        MainWindow.setTabOrder(self.cycleListPending, self.cycleListInProgress)
        MainWindow.setTabOrder(self.cycleListInProgress, self.startQC)
        MainWindow.setTabOrder(self.startQC, self.plainTextEdit)
        MainWindow.setTabOrder(self.plainTextEdit, self.imageJPanel2)
        MainWindow.setTabOrder(self.imageJPanel2, self.objectFC)
        MainWindow.setTabOrder(self.objectFC, self.objectLane)
        MainWindow.setTabOrder(self.objectLane, self.objectPosition)
        MainWindow.setTabOrder(self.objectPosition, self.objectDisplay)
        MainWindow.setTabOrder(self.objectDisplay, self.rawCycleList)
        MainWindow.setTabOrder(self.rawCycleList, self.rawFlowcell)
        MainWindow.setTabOrder(self.rawFlowcell, self.rawLane)
        MainWindow.setTabOrder(self.rawLane, self.rawImage)
        MainWindow.setTabOrder(self.rawImage, self.rawRed)
        MainWindow.setTabOrder(self.rawRed, self.rawGreen)
        MainWindow.setTabOrder(self.rawGreen, self.rawBlue)
        MainWindow.setTabOrder(self.rawBlue, self.rawDisplay)
        MainWindow.setTabOrder(self.rawDisplay, self.histogramFileList)
        MainWindow.setTabOrder(self.histogramFileList, self.histogramFlowcell)
        MainWindow.setTabOrder(self.histogramFlowcell, self.histogramLane)
        MainWindow.setTabOrder(self.histogramLane, self.histogramThreshold)
        MainWindow.setTabOrder(self.histogramThreshold, self.histogramDrawHistogram)
        MainWindow.setTabOrder(self.histogramDrawHistogram, self.histogramCutoff0_0)
        MainWindow.setTabOrder(self.histogramCutoff0_0, self.histogramCutoff0_1)
        MainWindow.setTabOrder(self.histogramCutoff0_1, self.histogramCutoff0_2)
        MainWindow.setTabOrder(self.histogramCutoff0_2, self.histogramCutoff0_3)
        MainWindow.setTabOrder(self.histogramCutoff0_3, self.histogramCutoff0_4)
        MainWindow.setTabOrder(self.histogramCutoff0_4, self.histogramCutoff0_5)
        MainWindow.setTabOrder(self.histogramCutoff0_5, self.histogramCutoff0_6)
        MainWindow.setTabOrder(self.histogramCutoff0_6, self.histogramCutoff0_7)
        MainWindow.setTabOrder(self.histogramCutoff0_7, self.histogramCutoff1_0)
        MainWindow.setTabOrder(self.histogramCutoff1_0, self.histogramCutoff1_1)
        MainWindow.setTabOrder(self.histogramCutoff1_1, self.histogramCutoff1_2)
        MainWindow.setTabOrder(self.histogramCutoff1_2, self.histogramCutoff1_3)
        MainWindow.setTabOrder(self.histogramCutoff1_3, self.histogramCutoff1_4)
        MainWindow.setTabOrder(self.histogramCutoff1_4, self.histogramCutoff1_5)
        MainWindow.setTabOrder(self.histogramCutoff1_5, self.histogramCutoff1_6)
        MainWindow.setTabOrder(self.histogramCutoff1_6, self.histogramCutoff1_7)
        MainWindow.setTabOrder(self.histogramCutoff1_7, self.histogramLoadCutoffs)
        MainWindow.setTabOrder(self.histogramLoadCutoffs, self.histogramSetCutoffs)
        MainWindow.setTabOrder(self.histogramSetCutoffs, self.histogramGenerateData)
        MainWindow.setTabOrder(self.histogramGenerateData, self.histogramSingleButton)
        MainWindow.setTabOrder(self.histogramSingleButton, self.histogramCycleButton)
        MainWindow.setTabOrder(self.histogramCycleButton, self.histogramOutputWindow)
        MainWindow.setTabOrder(self.histogramOutputWindow, self.basecallerAvailCyclesList)
        MainWindow.setTabOrder(self.basecallerAvailCyclesList, self.basecallerAddButton)
        MainWindow.setTabOrder(self.basecallerAddButton, self.basecallerRemoveButton)
        MainWindow.setTabOrder(self.basecallerRemoveButton, self.basecallerAddAllButton)
        MainWindow.setTabOrder(self.basecallerAddAllButton, self.basecallerReadOrderList)
        MainWindow.setTabOrder(self.basecallerReadOrderList, self.basecallerUpButton)
        MainWindow.setTabOrder(self.basecallerUpButton, self.basecallerDownButton)
        MainWindow.setTabOrder(self.basecallerDownButton, self.basecallerReadfileFN)
        MainWindow.setTabOrder(self.basecallerReadfileFN, self.jSlider1)
        MainWindow.setTabOrder(self.jSlider1, self.jSlider2)
        MainWindow.setTabOrder(self.jSlider2, self.basecallerRunBasecallerButton)
        MainWindow.setTabOrder(self.basecallerRunBasecallerButton, self.basecallerOutputWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.polonator_initialize.setText(QtGui.QApplication.translate("MainWindow", "Initialize", None, QtGui.QApplication.UnicodeUTF8))
        self.polonator_process.setText(QtGui.QApplication.translate("MainWindow", "Process images", None, QtGui.QApplication.UnicodeUTF8))
        self.polonator_initializestatus.setText(QtGui.QApplication.translate("MainWindow", "NOT RUNNING", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Pipeline initialization is:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "CURRENT STATUS:", None, QtGui.QApplication.UnicodeUTF8))
        self.polonator_processorstatus.setText(QtGui.QApplication.translate("MainWindow", "NOT RUNNING", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Image processing is:", None, QtGui.QApplication.UnicodeUTF8))
        self.polonator_kill.setText(QtGui.QApplication.translate("MainWindow", "STOP ALL PROCESSING SOFTWARE", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "CURRENT EXPERIMENT:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "updateProcesses", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), QtGui.QApplication.translate("MainWindow", "Polonator", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Pending Cycles", None, QtGui.QApplication.UnicodeUTF8))
        self.startQC.setText(QtGui.QApplication.translate("MainWindow", "QC", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "In Progress", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.cycleListPending.isSortingEnabled()
        self.cycleListPending.setSortingEnabled(False)
        self.cycleListPending.item(0).setText(QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.cycleListPending.item(1).setText(QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.cycleListPending.item(2).setText(QtGui.QApplication.translate("MainWindow", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.cycleListPending.item(3).setText(QtGui.QApplication.translate("MainWindow", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.cycleListPending.item(4).setText(QtGui.QApplication.translate("MainWindow", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.cycleListPending.setSortingEnabled(__sortingEnabled)
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Complete Cycles", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_4.setText(QtGui.QApplication.translate("MainWindow", "updateQualityLists", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Cycle Quality", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "Cycle Alignment", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Flowcell", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Lane", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Position", None, QtGui.QApplication.UnicodeUTF8))
        self.objectFC.setItemText(0, QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.objectFC.setItemText(1, QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.objectLane.setItemText(0, QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.objectLane.setItemText(1, QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.objectLane.setItemText(2, QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.objectLane.setItemText(3, QtGui.QApplication.translate("MainWindow", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.objectLane.setItemText(4, QtGui.QApplication.translate("MainWindow", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.objectLane.setItemText(5, QtGui.QApplication.translate("MainWindow", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.objectLane.setItemText(6, QtGui.QApplication.translate("MainWindow", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.objectLane.setItemText(7, QtGui.QApplication.translate("MainWindow", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.objectDisplay.setText(QtGui.QApplication.translate("MainWindow", "Display objects", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("MainWindow", "Object Finder", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.rawCycleList.isSortingEnabled()
        self.rawCycleList.setSortingEnabled(False)
        self.rawCycleList.item(0).setText(QtGui.QApplication.translate("MainWindow", "Item 1", None, QtGui.QApplication.UnicodeUTF8))
        self.rawCycleList.item(1).setText(QtGui.QApplication.translate("MainWindow", "Item 2", None, QtGui.QApplication.UnicodeUTF8))
        self.rawCycleList.item(2).setText(QtGui.QApplication.translate("MainWindow", "Item 3", None, QtGui.QApplication.UnicodeUTF8))
        self.rawCycleList.item(3).setText(QtGui.QApplication.translate("MainWindow", "Item 4", None, QtGui.QApplication.UnicodeUTF8))
        self.rawCycleList.item(4).setText(QtGui.QApplication.translate("MainWindow", "Item 5", None, QtGui.QApplication.UnicodeUTF8))
        self.rawCycleList.setSortingEnabled(__sortingEnabled)
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Flowcell", None, QtGui.QApplication.UnicodeUTF8))
        self.rawFlowcell.setItemText(0, QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.rawFlowcell.setItemText(1, QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.rawLane.setItemText(0, QtGui.QApplication.translate("MainWindow", "00", None, QtGui.QApplication.UnicodeUTF8))
        self.rawLane.setItemText(1, QtGui.QApplication.translate("MainWindow", "01", None, QtGui.QApplication.UnicodeUTF8))
        self.rawLane.setItemText(2, QtGui.QApplication.translate("MainWindow", "02", None, QtGui.QApplication.UnicodeUTF8))
        self.rawLane.setItemText(3, QtGui.QApplication.translate("MainWindow", "03", None, QtGui.QApplication.UnicodeUTF8))
        self.rawLane.setItemText(4, QtGui.QApplication.translate("MainWindow", "04", None, QtGui.QApplication.UnicodeUTF8))
        self.rawLane.setItemText(5, QtGui.QApplication.translate("MainWindow", "05", None, QtGui.QApplication.UnicodeUTF8))
        self.rawLane.setItemText(6, QtGui.QApplication.translate("MainWindow", "06", None, QtGui.QApplication.UnicodeUTF8))
        self.rawLane.setItemText(7, QtGui.QApplication.translate("MainWindow", "07", None, QtGui.QApplication.UnicodeUTF8))
        self.rawRed.setItemText(0, QtGui.QApplication.translate("MainWindow", "A", None, QtGui.QApplication.UnicodeUTF8))
        self.rawRed.setItemText(1, QtGui.QApplication.translate("MainWindow", "C", None, QtGui.QApplication.UnicodeUTF8))
        self.rawRed.setItemText(2, QtGui.QApplication.translate("MainWindow", "G", None, QtGui.QApplication.UnicodeUTF8))
        self.rawRed.setItemText(3, QtGui.QApplication.translate("MainWindow", "T", None, QtGui.QApplication.UnicodeUTF8))
        self.rawRed.setItemText(4, QtGui.QApplication.translate("MainWindow", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.rawGreen.setItemText(0, QtGui.QApplication.translate("MainWindow", "A", None, QtGui.QApplication.UnicodeUTF8))
        self.rawGreen.setItemText(1, QtGui.QApplication.translate("MainWindow", "C", None, QtGui.QApplication.UnicodeUTF8))
        self.rawGreen.setItemText(2, QtGui.QApplication.translate("MainWindow", "G", None, QtGui.QApplication.UnicodeUTF8))
        self.rawGreen.setItemText(3, QtGui.QApplication.translate("MainWindow", "T", None, QtGui.QApplication.UnicodeUTF8))
        self.rawGreen.setItemText(4, QtGui.QApplication.translate("MainWindow", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.rawBlue.setItemText(0, QtGui.QApplication.translate("MainWindow", "A", None, QtGui.QApplication.UnicodeUTF8))
        self.rawBlue.setItemText(1, QtGui.QApplication.translate("MainWindow", "C", None, QtGui.QApplication.UnicodeUTF8))
        self.rawBlue.setItemText(2, QtGui.QApplication.translate("MainWindow", "G", None, QtGui.QApplication.UnicodeUTF8))
        self.rawBlue.setItemText(3, QtGui.QApplication.translate("MainWindow", "T", None, QtGui.QApplication.UnicodeUTF8))
        self.rawBlue.setItemText(4, QtGui.QApplication.translate("MainWindow", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Lane", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "Image", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "Red", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "Green", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "Blue", None, QtGui.QApplication.UnicodeUTF8))
        self.rawDisplay.setText(QtGui.QApplication.translate("MainWindow", "Display color overlay", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QtGui.QApplication.translate("MainWindow", "Raw Images", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.histogramFileList.isSortingEnabled()
        self.histogramFileList.setSortingEnabled(False)
        self.histogramFileList.item(0).setText(QtGui.QApplication.translate("MainWindow", "Item 1", None, QtGui.QApplication.UnicodeUTF8))
        self.histogramFileList.item(1).setText(QtGui.QApplication.translate("MainWindow", "Item 2", None, QtGui.QApplication.UnicodeUTF8))
        self.histogramFileList.item(2).setText(QtGui.QApplication.translate("MainWindow", "Item 3", None, QtGui.QApplication.UnicodeUTF8))
        self.histogramFileList.item(3).setText(QtGui.QApplication.translate("MainWindow", "Item 4", None, QtGui.QApplication.UnicodeUTF8))
        self.histogramFileList.item(4).setText(QtGui.QApplication.translate("MainWindow", "Item 5", None, QtGui.QApplication.UnicodeUTF8))
        self.histogramFileList.setSortingEnabled(__sortingEnabled)
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "Flowcell", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", "Lane", None, QtGui.QApplication.UnicodeUTF8))
        self.histogramThreshold.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.histogramFlowcell.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.histogramLane.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.histogramDrawHistogram.setText(QtGui.QApplication.translate("MainWindow", "Display histogram", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("MainWindow", "Threshold", None, QtGui.QApplication.UnicodeUTF8))
        self.histogramCutoff0_2.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.histogramCutoff0_3.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("MainWindow", "Lane 0", None, QtGui.QApplication.UnicodeUTF8))
        self.histogramCutoff1_7.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("MainWindow", "Lane 5", None, QtGui.QApplication.UnicodeUTF8))
        self.histogramCutoff0_1.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("MainWindow", "Lane 3", None, QtGui.QApplication.UnicodeUTF8))
        self.histogramCutoff0_7.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_68.setText(QtGui.QApplication.translate("MainWindow", "Lane 0", None, QtGui.QApplication.UnicodeUTF8))
        self.histogramCutoff0_0.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.histogramCutoff1_6.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.histogramCutoff1_4.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.histogramCutoff1_5.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("MainWindow", "Lane 4", None, QtGui.QApplication.UnicodeUTF8))
        self.histogramCutoff1_1.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.histogramCutoff1_2.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.histogramCutoff0_4.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_70.setText(QtGui.QApplication.translate("MainWindow", "Lane 2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_67.setText(QtGui.QApplication.translate("MainWindow", "Flowcell 1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("MainWindow", "Basecalling Cutoffs", None, QtGui.QApplication.UnicodeUTF8))
        self.label_73.setText(QtGui.QApplication.translate("MainWindow", "Lane 5", None, QtGui.QApplication.UnicodeUTF8))
        self.histogramCutoff1_3.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("MainWindow", "Lane 6", None, QtGui.QApplication.UnicodeUTF8))
        self.label_71.setText(QtGui.QApplication.translate("MainWindow", "Lane 3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_72.setText(QtGui.QApplication.translate("MainWindow", "Lane 4", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("MainWindow", "Lane 2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("MainWindow", "Flowcell 0", None, QtGui.QApplication.UnicodeUTF8))
        self.histogramCutoff0_6.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_75.setText(QtGui.QApplication.translate("MainWindow", "Lane 7", None, QtGui.QApplication.UnicodeUTF8))
        self.label_74.setText(QtGui.QApplication.translate("MainWindow", "Lane 6", None, QtGui.QApplication.UnicodeUTF8))
        self.histogramCutoff1_0.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setText(QtGui.QApplication.translate("MainWindow", "Lane 1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_69.setText(QtGui.QApplication.translate("MainWindow", "Lane 1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("MainWindow", "Lane 7", None, QtGui.QApplication.UnicodeUTF8))
        self.histogramCutoff0_5.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.histogramSingleButton.setText(QtGui.QApplication.translate("MainWindow", "Single", None, QtGui.QApplication.UnicodeUTF8))
        self.histogramGenerateData.setText(QtGui.QApplication.translate("MainWindow", "GENERATE DATA", None, QtGui.QApplication.UnicodeUTF8))
        self.histogramSetCutoffs.setText(QtGui.QApplication.translate("MainWindow", "SET CUTOFFS", None, QtGui.QApplication.UnicodeUTF8))
        self.histogramCycleButton.setText(QtGui.QApplication.translate("MainWindow", "Cycle", None, QtGui.QApplication.UnicodeUTF8))
        self.histogramLoadCutoffs.setText(QtGui.QApplication.translate("MainWindow", "LOAD CUTOFFS", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setText(QtGui.QApplication.translate("MainWindow", "initializeHistogramCutoffFields", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), QtGui.QApplication.translate("MainWindow", "Histogram", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("MainWindow", "Available cycles", None, QtGui.QApplication.UnicodeUTF8))
        self.basecallerUpButton.setText(QtGui.QApplication.translate("MainWindow", "Up", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("MainWindow", "Read order", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.basecallerReadOrderList.isSortingEnabled()
        self.basecallerReadOrderList.setSortingEnabled(False)
        self.basecallerReadOrderList.item(0).setText(QtGui.QApplication.translate("MainWindow", "readorder1", None, QtGui.QApplication.UnicodeUTF8))
        self.basecallerReadOrderList.item(1).setText(QtGui.QApplication.translate("MainWindow", "readorder2", None, QtGui.QApplication.UnicodeUTF8))
        self.basecallerReadOrderList.item(2).setText(QtGui.QApplication.translate("MainWindow", "readorder3", None, QtGui.QApplication.UnicodeUTF8))
        self.basecallerReadOrderList.item(3).setText(QtGui.QApplication.translate("MainWindow", "readorder4", None, QtGui.QApplication.UnicodeUTF8))
        self.basecallerReadOrderList.setSortingEnabled(__sortingEnabled)
        self.basecallerDownButton.setText(QtGui.QApplication.translate("MainWindow", "Down", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.basecallerAvailCyclesList.isSortingEnabled()
        self.basecallerAvailCyclesList.setSortingEnabled(False)
        self.basecallerAvailCyclesList.item(0).setText(QtGui.QApplication.translate("MainWindow", "Item 1", None, QtGui.QApplication.UnicodeUTF8))
        self.basecallerAvailCyclesList.item(1).setText(QtGui.QApplication.translate("MainWindow", "Item 2", None, QtGui.QApplication.UnicodeUTF8))
        self.basecallerAvailCyclesList.item(2).setText(QtGui.QApplication.translate("MainWindow", "Item 3", None, QtGui.QApplication.UnicodeUTF8))
        self.basecallerAvailCyclesList.item(3).setText(QtGui.QApplication.translate("MainWindow", "Item 4", None, QtGui.QApplication.UnicodeUTF8))
        self.basecallerAvailCyclesList.item(4).setText(QtGui.QApplication.translate("MainWindow", "Item 5", None, QtGui.QApplication.UnicodeUTF8))
        self.basecallerAvailCyclesList.setSortingEnabled(__sortingEnabled)
        self.basecallerAddAllButton.setText(QtGui.QApplication.translate("MainWindow", "ADD ALL -->", None, QtGui.QApplication.UnicodeUTF8))
        self.basecallerRemoveButton.setText(QtGui.QApplication.translate("MainWindow", "<-- REMOVE", None, QtGui.QApplication.UnicodeUTF8))
        self.basecallerAddButton.setText(QtGui.QApplication.translate("MainWindow", "ADD -->", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("MainWindow", "update_basecaller AvailableList", None, QtGui.QApplication.UnicodeUTF8))
        self.basecallerRunBasecallerButton.setText(QtGui.QApplication.translate("MainWindow", "RUN BASECALLER", None, QtGui.QApplication.UnicodeUTF8))
        self.basecallerPercentToKeepLabel.setText(QtGui.QApplication.translate("MainWindow", "50", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("MainWindow", "Base name of readfile", None, QtGui.QApplication.UnicodeUTF8))
        self.basecallerPercentBGSubtractLabel.setText(QtGui.QApplication.translate("MainWindow", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.basecallerReadfileFN.setText(QtGui.QApplication.translate("MainWindow", "Default", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("MainWindow", "Percentage of data to keep:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_76.setText(QtGui.QApplication.translate("MainWindow", "Percent background subtract:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), QtGui.QApplication.translate("MainWindow", "Basecaller", None, QtGui.QApplication.UnicodeUTF8))
        self.label_77.setText(QtGui.QApplication.translate("MainWindow", "Polonator Data Processing Control Interface", None, QtGui.QApplication.UnicodeUTF8))
        self.label_78.setText(QtGui.QApplication.translate("MainWindow", "Version", None, QtGui.QApplication.UnicodeUTF8))
        self.label_79.setText(QtGui.QApplication.translate("MainWindow", "Date", None, QtGui.QApplication.UnicodeUTF8))
        self.label_80.setText(QtGui.QApplication.translate("MainWindow", "Written by Greg Porreca (Church Lab, Harvard Medical School)", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))

