# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Polonator\Documents\Qt Polonator\polonatorprocessor_01.ui'
#
# Created: Fri Jul 16 15:18:13 2010
#      by: PyQt4 UI code generator 4.5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1260, 802)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(681, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        MainWindow.setFont(font)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 1249, 769))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtGui.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.pushButton = QtGui.QPushButton(self.tab_1)
        self.pushButton.setEnabled(False)
        self.pushButton.setGeometry(QtCore.QRect(50, 690, 111, 23))
        self.pushButton.setObjectName("pushButton")
        self.polonator_textarea = QtGui.QTextEdit(self.tab_1)
        self.polonator_textarea.setGeometry(QtCore.QRect(520, 10, 701, 671))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.polonator_textarea.sizePolicy().hasHeightForWidth())
        self.polonator_textarea.setSizePolicy(sizePolicy)
        self.polonator_textarea.setMinimumSize(QtCore.QSize(701, 0))
        self.polonator_textarea.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.polonator_textarea.setFont(font)
        self.polonator_textarea.setObjectName("polonator_textarea")
        self.frame_3 = QtGui.QFrame(self.tab_1)
        self.frame_3.setGeometry(QtCore.QRect(10, 10, 501, 671))
        self.frame_3.setFrameShape(QtGui.QFrame.Box)
        self.frame_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayoutWidget_10 = QtGui.QWidget(self.frame_3)
        self.verticalLayoutWidget_10.setGeometry(QtCore.QRect(10, 10, 481, 651))
        self.verticalLayoutWidget_10.setObjectName("verticalLayoutWidget_10")
        self.verticalLayout_21 = QtGui.QVBoxLayout(self.verticalLayoutWidget_10)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label = QtGui.QLabel(self.verticalLayoutWidget_10)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_21.addWidget(self.label)
        self.polonator_experiment = QtGui.QLabel(self.verticalLayoutWidget_10)
        self.polonator_experiment.setMinimumSize(QtCore.QSize(0, 25))
        self.polonator_experiment.setFrameShape(QtGui.QFrame.Box)
        self.polonator_experiment.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.polonator_experiment.setWordWrap(True)
        self.polonator_experiment.setObjectName("polonator_experiment")
        self.verticalLayout_21.addWidget(self.polonator_experiment)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.polonator_initialize = QtGui.QPushButton(self.verticalLayoutWidget_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.polonator_initialize.sizePolicy().hasHeightForWidth())
        self.polonator_initialize.setSizePolicy(sizePolicy)
        self.polonator_initialize.setMinimumSize(QtCore.QSize(0, 50))
        self.polonator_initialize.setObjectName("polonator_initialize")
        self.horizontalLayout_3.addWidget(self.polonator_initialize)
        self.polonator_process = QtGui.QPushButton(self.verticalLayoutWidget_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.polonator_process.sizePolicy().hasHeightForWidth())
        self.polonator_process.setSizePolicy(sizePolicy)
        self.polonator_process.setMinimumSize(QtCore.QSize(0, 50))
        self.polonator_process.setProperty("enterEvent", QtCore.QVariant(False))
        self.polonator_process.setObjectName("polonator_process")
        self.horizontalLayout_3.addWidget(self.polonator_process)
        self.verticalLayout_21.addLayout(self.horizontalLayout_3)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_21.addItem(spacerItem)
        self.label_2 = QtGui.QLabel(self.verticalLayoutWidget_10)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_21.addWidget(self.label_2)
        self.formLayout_8 = QtGui.QFormLayout()
        self.formLayout_8.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_8.setObjectName("formLayout_8")
        self.label_3 = QtGui.QLabel(self.verticalLayoutWidget_10)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.formLayout_8.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_3)
        self.polonator_processorstatus = QtGui.QLabel(self.verticalLayoutWidget_10)
        self.polonator_processorstatus.setMinimumSize(QtCore.QSize(0, 25))
        self.polonator_processorstatus.setFrameShape(QtGui.QFrame.Box)
        self.polonator_processorstatus.setObjectName("polonator_processorstatus")
        self.formLayout_8.setWidget(0, QtGui.QFormLayout.FieldRole, self.polonator_processorstatus)
        self.verticalLayout_21.addLayout(self.formLayout_8)
        self.polonator_processorpath = QtGui.QLabel(self.verticalLayoutWidget_10)
        self.polonator_processorpath.setMinimumSize(QtCore.QSize(0, 50))
        self.polonator_processorpath.setFrameShape(QtGui.QFrame.Box)
        self.polonator_processorpath.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.polonator_processorpath.setObjectName("polonator_processorpath")
        self.verticalLayout_21.addWidget(self.polonator_processorpath)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_21.addItem(spacerItem1)
        self.formLayout_9 = QtGui.QFormLayout()
        self.formLayout_9.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_9.setObjectName("formLayout_9")
        self.label_5 = QtGui.QLabel(self.verticalLayoutWidget_10)
        self.label_5.setObjectName("label_5")
        self.formLayout_9.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_5)
        self.polonator_initializestatus = QtGui.QLabel(self.verticalLayoutWidget_10)
        self.polonator_initializestatus.setMinimumSize(QtCore.QSize(0, 25))
        self.polonator_initializestatus.setFrameShape(QtGui.QFrame.Box)
        self.polonator_initializestatus.setObjectName("polonator_initializestatus")
        self.formLayout_9.setWidget(0, QtGui.QFormLayout.FieldRole, self.polonator_initializestatus)
        self.verticalLayout_21.addLayout(self.formLayout_9)
        self.polonator_initializepath = QtGui.QLabel(self.verticalLayoutWidget_10)
        self.polonator_initializepath.setMinimumSize(QtCore.QSize(0, 50))
        self.polonator_initializepath.setFrameShape(QtGui.QFrame.Box)
        self.polonator_initializepath.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.polonator_initializepath.setObjectName("polonator_initializepath")
        self.verticalLayout_21.addWidget(self.polonator_initializepath)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_21.addItem(spacerItem2)
        self.polonator_kill = QtGui.QPushButton(self.verticalLayoutWidget_10)
        self.polonator_kill.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.polonator_kill.setFont(font)
        self.polonator_kill.setObjectName("polonator_kill")
        self.verticalLayout_21.addWidget(self.polonator_kill)
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.frame_13 = QtGui.QFrame(self.tab_2)
        self.frame_13.setGeometry(QtCore.QRect(10, 10, 571, 191))
        self.frame_13.setFrameShape(QtGui.QFrame.Box)
        self.frame_13.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_13.setObjectName("frame_13")
        self.plainTextEdit = QtGui.QPlainTextEdit(self.tab_2)
        self.plainTextEdit.setGeometry(QtCore.QRect(130, 280, 411, 301))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.pushButton_4 = QtGui.QPushButton(self.tab_2)
        self.pushButton_4.setEnabled(False)
        self.pushButton_4.setGeometry(QtCore.QRect(80, 230, 201, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayoutWidget_2 = QtGui.QWidget(self.tab_2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(20, 20, 551, 171))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.cycleListComplete = QtGui.QListWidget(self.gridLayoutWidget_2)
        self.cycleListComplete.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.cycleListComplete.setObjectName("cycleListComplete")
        self.gridLayout_3.addWidget(self.cycleListComplete, 1, 0, 1, 1)
        self.cycleListPending = QtGui.QListWidget(self.gridLayoutWidget_2)
        self.cycleListPending.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.cycleListPending.setObjectName("cycleListPending")
        self.gridLayout_3.addWidget(self.cycleListPending, 1, 1, 1, 1)
        self.cycleListInProgress = QtGui.QListWidget(self.gridLayoutWidget_2)
        self.cycleListInProgress.setObjectName("cycleListInProgress")
        self.gridLayout_3.addWidget(self.cycleListInProgress, 1, 2, 1, 1)
        self.label_7 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 0, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 0, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 0, 2, 1, 1)
        self.startQC = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.startQC.setObjectName("startQC")
        self.gridLayout_3.addWidget(self.startQC, 2, 1, 1, 1)
        self.gridLayoutWidget_3 = QtGui.QWidget(self.tab_2)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(590, 10, 631, 681))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_4 = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.imageJPanel1 = QtGui.QGraphicsView(self.gridLayoutWidget_3)
        self.imageJPanel1.setObjectName("imageJPanel1")
        self.gridLayout_4.addWidget(self.imageJPanel1, 0, 0, 1, 1)
        self.imageJPanel2 = QtGui.QGraphicsView(self.gridLayoutWidget_3)
        self.imageJPanel2.setObjectName("imageJPanel2")
        self.gridLayout_4.addWidget(self.imageJPanel2, 0, 1, 1, 1)
        self.alignXImageJPanel = QtGui.QGraphicsView(self.gridLayoutWidget_3)
        self.alignXImageJPanel.setObjectName("alignXImageJPanel")
        self.gridLayout_4.addWidget(self.alignXImageJPanel, 1, 0, 1, 1)
        self.alignYImageJPanel = QtGui.QGraphicsView(self.gridLayoutWidget_3)
        self.alignYImageJPanel.setObjectName("alignYImageJPanel")
        self.gridLayout_4.addWidget(self.alignYImageJPanel, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.frame = QtGui.QFrame(self.tab_4)
        self.frame.setGeometry(QtCore.QRect(10, 10, 211, 151))
        self.frame.setFrameShape(QtGui.QFrame.Box)
        self.frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.verticalLayoutWidget_5 = QtGui.QWidget(self.frame)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(10, 10, 191, 131))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_10 = QtGui.QLabel(self.verticalLayoutWidget_5)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_4.addWidget(self.label_10)
        self.objectFC = QtGui.QComboBox(self.verticalLayoutWidget_5)
        self.objectFC.setObjectName("objectFC")
        self.objectFC.addItem(QtCore.QString())
        self.objectFC.addItem(QtCore.QString())
        self.horizontalLayout_4.addWidget(self.objectFC)
        self.verticalLayout_9.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_11 = QtGui.QLabel(self.verticalLayoutWidget_5)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_5.addWidget(self.label_11)
        self.objectLane = QtGui.QComboBox(self.verticalLayoutWidget_5)
        self.objectLane.setObjectName("objectLane")
        self.objectLane.addItem(QtCore.QString())
        self.objectLane.addItem(QtCore.QString())
        self.objectLane.addItem(QtCore.QString())
        self.objectLane.addItem(QtCore.QString())
        self.objectLane.addItem(QtCore.QString())
        self.objectLane.addItem(QtCore.QString())
        self.objectLane.addItem(QtCore.QString())
        self.objectLane.addItem(QtCore.QString())
        self.horizontalLayout_5.addWidget(self.objectLane)
        self.verticalLayout_9.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_12 = QtGui.QLabel(self.verticalLayoutWidget_5)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_6.addWidget(self.label_12)
        self.objectPosition = QtGui.QSpinBox(self.verticalLayoutWidget_5)
        self.objectPosition.setObjectName("objectPosition")
        self.horizontalLayout_6.addWidget(self.objectPosition)
        self.verticalLayout_9.addLayout(self.horizontalLayout_6)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem3)
        self.objectDisplay = QtGui.QPushButton(self.verticalLayoutWidget_5)
        self.objectDisplay.setObjectName("objectDisplay")
        self.verticalLayout_9.addWidget(self.objectDisplay)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.frame_2 = QtGui.QFrame(self.tab_5)
        self.frame_2.setGeometry(QtCore.QRect(10, 10, 371, 351))
        self.frame_2.setFrameShape(QtGui.QFrame.Box)
        self.frame_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayoutWidget_11 = QtGui.QWidget(self.frame_2)
        self.verticalLayoutWidget_11.setGeometry(QtCore.QRect(10, 10, 351, 331))
        self.verticalLayoutWidget_11.setObjectName("verticalLayoutWidget_11")
        self.verticalLayout_22 = QtGui.QVBoxLayout(self.verticalLayoutWidget_11)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtGui.QLabel(self.verticalLayoutWidget_11)
        self.label_4.setEnabled(False)
        self.label_4.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.rawFlowcell = QtGui.QComboBox(self.verticalLayoutWidget_11)
        self.rawFlowcell.setEnabled(False)
        self.rawFlowcell.setObjectName("rawFlowcell")
        self.rawFlowcell.addItem(QtCore.QString())
        self.rawFlowcell.addItem(QtCore.QString())
        self.rawFlowcell.addItem(QtCore.QString())
        self.rawFlowcell.setItemText(2, "")
        self.verticalLayout_3.addWidget(self.rawFlowcell)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem4)
        self.label_6 = QtGui.QLabel(self.verticalLayoutWidget_11)
        self.label_6.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.rawLane = QtGui.QComboBox(self.verticalLayoutWidget_11)
        self.rawLane.setObjectName("rawLane")
        self.rawLane.addItem(QtCore.QString())
        self.rawLane.addItem(QtCore.QString())
        self.rawLane.addItem(QtCore.QString())
        self.rawLane.addItem(QtCore.QString())
        self.rawLane.addItem(QtCore.QString())
        self.rawLane.addItem(QtCore.QString())
        self.rawLane.addItem(QtCore.QString())
        self.rawLane.addItem(QtCore.QString())
        self.verticalLayout_3.addWidget(self.rawLane)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem5)
        self.label_13 = QtGui.QLabel(self.verticalLayoutWidget_11)
        self.label_13.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_3.addWidget(self.label_13)
        self.rawImage = QtGui.QSpinBox(self.verticalLayoutWidget_11)
        self.rawImage.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.rawImage.setMaximum(9999)
        self.rawImage.setObjectName("rawImage")
        self.verticalLayout_3.addWidget(self.rawImage)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem6)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 1, 1, 1, 1)
        self.rawCycleList = QtGui.QListWidget(self.verticalLayoutWidget_11)
        self.rawCycleList.setObjectName("rawCycleList")
        self.gridLayout_2.addWidget(self.rawCycleList, 1, 0, 1, 1)
        self.label_37 = QtGui.QLabel(self.verticalLayoutWidget_11)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_37.setFont(font)
        self.label_37.setAlignment(QtCore.Qt.AlignCenter)
        self.label_37.setObjectName("label_37")
        self.gridLayout_2.addWidget(self.label_37, 0, 0, 1, 1)
        self.verticalLayout_22.addLayout(self.gridLayout_2)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_14 = QtGui.QLabel(self.verticalLayoutWidget_11)
        self.label_14.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_4.addWidget(self.label_14)
        self.rawRed = QtGui.QComboBox(self.verticalLayoutWidget_11)
        self.rawRed.setObjectName("rawRed")
        self.rawRed.addItem(QtCore.QString())
        self.rawRed.addItem(QtCore.QString())
        self.rawRed.addItem(QtCore.QString())
        self.rawRed.addItem(QtCore.QString())
        self.rawRed.addItem(QtCore.QString())
        self.verticalLayout_4.addWidget(self.rawRed)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_15 = QtGui.QLabel(self.verticalLayoutWidget_11)
        self.label_15.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_5.addWidget(self.label_15)
        self.rawGreen = QtGui.QComboBox(self.verticalLayoutWidget_11)
        self.rawGreen.setObjectName("rawGreen")
        self.rawGreen.addItem(QtCore.QString())
        self.rawGreen.addItem(QtCore.QString())
        self.rawGreen.addItem(QtCore.QString())
        self.rawGreen.addItem(QtCore.QString())
        self.rawGreen.addItem(QtCore.QString())
        self.verticalLayout_5.addWidget(self.rawGreen)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_16 = QtGui.QLabel(self.verticalLayoutWidget_11)
        self.label_16.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_6.addWidget(self.label_16)
        self.rawBlue = QtGui.QComboBox(self.verticalLayoutWidget_11)
        self.rawBlue.setObjectName("rawBlue")
        self.rawBlue.addItem(QtCore.QString())
        self.rawBlue.addItem(QtCore.QString())
        self.rawBlue.addItem(QtCore.QString())
        self.rawBlue.addItem(QtCore.QString())
        self.rawBlue.addItem(QtCore.QString())
        self.verticalLayout_6.addWidget(self.rawBlue)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.verticalLayout_22.addLayout(self.horizontalLayout_2)
        self.rawDisplay = QtGui.QPushButton(self.verticalLayoutWidget_11)
        self.rawDisplay.setObjectName("rawDisplay")
        self.verticalLayout_22.addWidget(self.rawDisplay)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.pushButton_3 = QtGui.QPushButton(self.tab_6)
        self.pushButton_3.setEnabled(False)
        self.pushButton_3.setGeometry(QtCore.QRect(810, 0, 201, 16))
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayoutWidget_6 = QtGui.QWidget(self.tab_6)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(10, 10, 1211, 738))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_11.setSpacing(6)
        self.horizontalLayout_11.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_34 = QtGui.QLabel(self.horizontalLayoutWidget_6)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_34.setFont(font)
        self.label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.label_34.setObjectName("label_34")
        self.verticalLayout.addWidget(self.label_34)
        self.histogramFileList = QtGui.QListWidget(self.horizontalLayoutWidget_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.histogramFileList.sizePolicy().hasHeightForWidth())
        self.histogramFileList.setSizePolicy(sizePolicy)
        self.histogramFileList.setObjectName("histogramFileList")
        self.verticalLayout.addWidget(self.histogramFileList)
        self.horizontalLayout_11.addLayout(self.verticalLayout)
        self.verticalLayout_17 = QtGui.QVBoxLayout()
        self.verticalLayout_17.setSpacing(2)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.formLayout_4 = QtGui.QFormLayout()
        self.formLayout_4.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_17 = QtGui.QLabel(self.horizontalLayoutWidget_6)
        self.label_17.setObjectName("label_17")
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_17)
        self.label_18 = QtGui.QLabel(self.horizontalLayoutWidget_6)
        self.label_18.setObjectName("label_18")
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_18)
        self.label_19 = QtGui.QLabel(self.horizontalLayoutWidget_6)
        self.label_19.setObjectName("label_19")
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_19)
        self.histogramThreshold = QtGui.QLineEdit(self.horizontalLayoutWidget_6)
        self.histogramThreshold.setObjectName("histogramThreshold")
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.histogramThreshold)
        self.histogramLane = QtGui.QLineEdit(self.horizontalLayoutWidget_6)
        self.histogramLane.setObjectName("histogramLane")
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.histogramLane)
        self.histogramFlowcell = QtGui.QLineEdit(self.horizontalLayoutWidget_6)
        self.histogramFlowcell.setObjectName("histogramFlowcell")
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.histogramFlowcell)
        self.verticalLayout_17.addLayout(self.formLayout_4)
        self.histogramDrawHistogram = QtGui.QPushButton(self.horizontalLayoutWidget_6)
        self.histogramDrawHistogram.setObjectName("histogramDrawHistogram")
        self.verticalLayout_17.addWidget(self.histogramDrawHistogram)
        self.line = QtGui.QFrame(self.horizontalLayoutWidget_6)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_17.addWidget(self.line)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_17.addItem(spacerItem7)
        self.label_20 = QtGui.QLabel(self.horizontalLayoutWidget_6)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_17.addWidget(self.label_20)
        self.label_21 = QtGui.QLabel(self.horizontalLayoutWidget_6)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_17.addWidget(self.label_21)
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setVerticalSpacing(7)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_32 = QtGui.QLabel(self.horizontalLayoutWidget_6)
        self.label_32.setObjectName("label_32")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_32)
        self.histogramCutoff0_0 = QtGui.QLineEdit(self.horizontalLayoutWidget_6)
        self.histogramCutoff0_0.setObjectName("histogramCutoff0_0")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.histogramCutoff0_0)
        self.label_33 = QtGui.QLabel(self.horizontalLayoutWidget_6)
        self.label_33.setObjectName("label_33")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_33)
        self.histogramCutoff0_1 = QtGui.QLineEdit(self.horizontalLayoutWidget_6)
        self.histogramCutoff0_1.setObjectName("histogramCutoff0_1")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.histogramCutoff0_1)
        self.label_22 = QtGui.QLabel(self.horizontalLayoutWidget_6)
        self.label_22.setObjectName("label_22")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_22)
        self.histogramCutoff0_2 = QtGui.QLineEdit(self.horizontalLayoutWidget_6)
        self.histogramCutoff0_2.setObjectName("histogramCutoff0_2")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.histogramCutoff0_2)
        self.label_23 = QtGui.QLabel(self.horizontalLayoutWidget_6)
        self.label_23.setObjectName("label_23")
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_23)
        self.histogramCutoff0_3 = QtGui.QLineEdit(self.horizontalLayoutWidget_6)
        self.histogramCutoff0_3.setObjectName("histogramCutoff0_3")
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.histogramCutoff0_3)
        self.label_24 = QtGui.QLabel(self.horizontalLayoutWidget_6)
        self.label_24.setObjectName("label_24")
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_24)
        self.histogramCutoff0_4 = QtGui.QLineEdit(self.horizontalLayoutWidget_6)
        self.histogramCutoff0_4.setObjectName("histogramCutoff0_4")
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.histogramCutoff0_4)
        self.label_25 = QtGui.QLabel(self.horizontalLayoutWidget_6)
        self.label_25.setObjectName("label_25")
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_25)
        self.histogramCutoff0_5 = QtGui.QLineEdit(self.horizontalLayoutWidget_6)
        self.histogramCutoff0_5.setObjectName("histogramCutoff0_5")
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.FieldRole, self.histogramCutoff0_5)
        self.label_26 = QtGui.QLabel(self.horizontalLayoutWidget_6)
        self.label_26.setObjectName("label_26")
        self.formLayout_2.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_26)
        self.histogramCutoff0_6 = QtGui.QLineEdit(self.horizontalLayoutWidget_6)
        self.histogramCutoff0_6.setObjectName("histogramCutoff0_6")
        self.formLayout_2.setWidget(6, QtGui.QFormLayout.FieldRole, self.histogramCutoff0_6)
        self.label_27 = QtGui.QLabel(self.horizontalLayoutWidget_6)
        self.label_27.setObjectName("label_27")
        self.formLayout_2.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_27)
        self.histogramCutoff0_7 = QtGui.QLineEdit(self.horizontalLayoutWidget_6)
        self.histogramCutoff0_7.setObjectName("histogramCutoff0_7")
        self.formLayout_2.setWidget(7, QtGui.QFormLayout.FieldRole, self.histogramCutoff0_7)
        self.verticalLayout_17.addLayout(self.formLayout_2)
        self.label_67 = QtGui.QLabel(self.horizontalLayoutWidget_6)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_67.setFont(font)
        self.label_67.setObjectName("label_67")
        self.verticalLayout_17.addWidget(self.label_67)
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setVerticalSpacing(7)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_68 = QtGui.QLabel(self.horizontalLayoutWidget_6)
        self.label_68.setObjectName("label_68")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_68)
        self.histogramCutoff1_0 = QtGui.QLineEdit(self.horizontalLayoutWidget_6)
        self.histogramCutoff1_0.setObjectName("histogramCutoff1_0")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.histogramCutoff1_0)
        self.label_69 = QtGui.QLabel(self.horizontalLayoutWidget_6)
        self.label_69.setObjectName("label_69")
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_69)
        self.histogramCutoff1_1 = QtGui.QLineEdit(self.horizontalLayoutWidget_6)
        self.histogramCutoff1_1.setObjectName("histogramCutoff1_1")
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.histogramCutoff1_1)
        self.label_70 = QtGui.QLabel(self.horizontalLayoutWidget_6)
        self.label_70.setObjectName("label_70")
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_70)
        self.histogramCutoff1_2 = QtGui.QLineEdit(self.horizontalLayoutWidget_6)
        self.histogramCutoff1_2.setObjectName("histogramCutoff1_2")
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.histogramCutoff1_2)
        self.label_71 = QtGui.QLabel(self.horizontalLayoutWidget_6)
        self.label_71.setObjectName("label_71")
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_71)
        self.histogramCutoff1_3 = QtGui.QLineEdit(self.horizontalLayoutWidget_6)
        self.histogramCutoff1_3.setObjectName("histogramCutoff1_3")
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.FieldRole, self.histogramCutoff1_3)
        self.label_72 = QtGui.QLabel(self.horizontalLayoutWidget_6)
        self.label_72.setObjectName("label_72")
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_72)
        self.histogramCutoff1_4 = QtGui.QLineEdit(self.horizontalLayoutWidget_6)
        self.histogramCutoff1_4.setObjectName("histogramCutoff1_4")
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.FieldRole, self.histogramCutoff1_4)
        self.label_73 = QtGui.QLabel(self.horizontalLayoutWidget_6)
        self.label_73.setObjectName("label_73")
        self.formLayout_3.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_73)
        self.histogramCutoff1_5 = QtGui.QLineEdit(self.horizontalLayoutWidget_6)
        self.histogramCutoff1_5.setObjectName("histogramCutoff1_5")
        self.formLayout_3.setWidget(5, QtGui.QFormLayout.FieldRole, self.histogramCutoff1_5)
        self.label_74 = QtGui.QLabel(self.horizontalLayoutWidget_6)
        self.label_74.setObjectName("label_74")
        self.formLayout_3.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_74)
        self.histogramCutoff1_6 = QtGui.QLineEdit(self.horizontalLayoutWidget_6)
        self.histogramCutoff1_6.setObjectName("histogramCutoff1_6")
        self.formLayout_3.setWidget(6, QtGui.QFormLayout.FieldRole, self.histogramCutoff1_6)
        self.label_75 = QtGui.QLabel(self.horizontalLayoutWidget_6)
        self.label_75.setObjectName("label_75")
        self.formLayout_3.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_75)
        self.histogramCutoff1_7 = QtGui.QLineEdit(self.horizontalLayoutWidget_6)
        self.histogramCutoff1_7.setObjectName("histogramCutoff1_7")
        self.formLayout_3.setWidget(7, QtGui.QFormLayout.FieldRole, self.histogramCutoff1_7)
        self.verticalLayout_17.addLayout(self.formLayout_3)
        self.histogramImportCutoffs = QtGui.QPushButton(self.horizontalLayoutWidget_6)
        self.histogramImportCutoffs.setObjectName("histogramImportCutoffs")
        self.verticalLayout_17.addWidget(self.histogramImportCutoffs)
        self.histogramExportCutoffs = QtGui.QPushButton(self.horizontalLayoutWidget_6)
        self.histogramExportCutoffs.setObjectName("histogramExportCutoffs")
        self.verticalLayout_17.addWidget(self.histogramExportCutoffs)
        self.histogramGenerateData = QtGui.QPushButton(self.horizontalLayoutWidget_6)
        self.histogramGenerateData.setObjectName("histogramGenerateData")
        self.verticalLayout_17.addWidget(self.histogramGenerateData)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.histogramSingleButton = QtGui.QRadioButton(self.horizontalLayoutWidget_6)
        self.histogramSingleButton.setObjectName("histogramSingleButton")
        self.horizontalLayout_10.addWidget(self.histogramSingleButton)
        self.histogramCycleButton = QtGui.QRadioButton(self.horizontalLayoutWidget_6)
        self.histogramCycleButton.setChecked(True)
        self.histogramCycleButton.setObjectName("histogramCycleButton")
        self.horizontalLayout_10.addWidget(self.histogramCycleButton)
        self.verticalLayout_17.addLayout(self.horizontalLayout_10)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_17.addItem(spacerItem8)
        self.line_3 = QtGui.QFrame(self.horizontalLayoutWidget_6)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_17.addWidget(self.line_3)
        self.horizontalLayout_11.addLayout(self.verticalLayout_17)
        self.histogramOutputWindow = QtGui.QTextEdit(self.horizontalLayoutWidget_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.histogramOutputWindow.sizePolicy().hasHeightForWidth())
        self.histogramOutputWindow.setSizePolicy(sizePolicy)
        self.histogramOutputWindow.setMinimumSize(QtCore.QSize(775, 0))
        self.histogramOutputWindow.setObjectName("histogramOutputWindow")
        self.horizontalLayout_11.addWidget(self.histogramOutputWindow)
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.pushButton_2 = QtGui.QPushButton(self.tab_7)
        self.pushButton_2.setEnabled(False)
        self.pushButton_2.setGeometry(QtCore.QRect(130, 670, 191, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayoutWidget = QtGui.QWidget(self.tab_7)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 1211, 651))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_20 = QtGui.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.basecallerAvailCyclesList = QtGui.QListWidget(self.horizontalLayoutWidget)
        self.basecallerAvailCyclesList.setMinimumSize(QtCore.QSize(0, 250))
        self.basecallerAvailCyclesList.setObjectName("basecallerAvailCyclesList")
        self.gridLayout_6.addWidget(self.basecallerAvailCyclesList, 1, 0, 1, 1)
        self.basecallerReadOrderList = QtGui.QListWidget(self.horizontalLayoutWidget)
        self.basecallerReadOrderList.setObjectName("basecallerReadOrderList")
        self.gridLayout_6.addWidget(self.basecallerReadOrderList, 1, 2, 1, 1)
        self.label_28 = QtGui.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_28.setFont(font)
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.gridLayout_6.addWidget(self.label_28, 0, 0, 1, 1)
        self.label_29 = QtGui.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_29.setFont(font)
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.gridLayout_6.addWidget(self.label_29, 0, 2, 1, 1)
        self.verticalLayout_16 = QtGui.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        spacerItem9 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_16.addItem(spacerItem9)
        self.basecallerAddButton = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.basecallerAddButton.setObjectName("basecallerAddButton")
        self.verticalLayout_16.addWidget(self.basecallerAddButton)
        self.basecallerRemoveButton = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.basecallerRemoveButton.setObjectName("basecallerRemoveButton")
        self.verticalLayout_16.addWidget(self.basecallerRemoveButton)
        self.basecallerAddAllButton = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.basecallerAddAllButton.setObjectName("basecallerAddAllButton")
        self.verticalLayout_16.addWidget(self.basecallerAddAllButton)
        spacerItem10 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_16.addItem(spacerItem10)
        self.gridLayout_6.addLayout(self.verticalLayout_16, 1, 1, 1, 1)
        self.verticalLayout_19 = QtGui.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        spacerItem11 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_19.addItem(spacerItem11)
        self.basecallerUpButton = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.basecallerUpButton.setObjectName("basecallerUpButton")
        self.verticalLayout_19.addWidget(self.basecallerUpButton)
        self.basecallerDownButton = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.basecallerDownButton.setObjectName("basecallerDownButton")
        self.verticalLayout_19.addWidget(self.basecallerDownButton)
        spacerItem12 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_19.addItem(spacerItem12)
        self.gridLayout_6.addLayout(self.verticalLayout_19, 1, 3, 1, 1)
        self.verticalLayout_20.addLayout(self.gridLayout_6)
        spacerItem13 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_20.addItem(spacerItem13)
        self.formLayout_5 = QtGui.QFormLayout()
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_30 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_30.setMinimumSize(QtCore.QSize(150, 0))
        self.label_30.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_30.setObjectName("label_30")
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_30)
        self.basecallerReadfileFN = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.basecallerReadfileFN.setObjectName("basecallerReadfileFN")
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.basecallerReadfileFN)
        self.verticalLayout_20.addLayout(self.formLayout_5)
        spacerItem14 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_20.addItem(spacerItem14)
        self.formLayout_6 = QtGui.QFormLayout()
        self.formLayout_6.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_6.setObjectName("formLayout_6")
        self.verticalLayout_20.addLayout(self.formLayout_6)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_31 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_31.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_14.addWidget(self.label_31)
        self.basecallerPercentToKeepLabel = QtGui.QLabel(self.horizontalLayoutWidget)
        self.basecallerPercentToKeepLabel.setFrameShape(QtGui.QFrame.Box)
        self.basecallerPercentToKeepLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.basecallerPercentToKeepLabel.setObjectName("basecallerPercentToKeepLabel")
        self.horizontalLayout_14.addWidget(self.basecallerPercentToKeepLabel)
        self.verticalLayout_20.addLayout(self.horizontalLayout_14)
        self.basecallerDataKeepSlider = QtGui.QSlider(self.horizontalLayoutWidget)
        self.basecallerDataKeepSlider.setMaximum(100)
        self.basecallerDataKeepSlider.setPageStep(10)
        self.basecallerDataKeepSlider.setSliderPosition(50)
        self.basecallerDataKeepSlider.setOrientation(QtCore.Qt.Horizontal)
        self.basecallerDataKeepSlider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.basecallerDataKeepSlider.setTickInterval(1)
        self.basecallerDataKeepSlider.setObjectName("basecallerDataKeepSlider")
        self.verticalLayout_20.addWidget(self.basecallerDataKeepSlider)
        spacerItem15 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_20.addItem(spacerItem15)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_76 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_76.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_76.setObjectName("label_76")
        self.horizontalLayout_15.addWidget(self.label_76)
        self.basecallerPercentBGSubtractLabel = QtGui.QLabel(self.horizontalLayoutWidget)
        self.basecallerPercentBGSubtractLabel.setFrameShape(QtGui.QFrame.Box)
        self.basecallerPercentBGSubtractLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.basecallerPercentBGSubtractLabel.setObjectName("basecallerPercentBGSubtractLabel")
        self.horizontalLayout_15.addWidget(self.basecallerPercentBGSubtractLabel)
        self.verticalLayout_20.addLayout(self.horizontalLayout_15)
        self.basecallerBackgroundSubtractSlider = QtGui.QSlider(self.horizontalLayoutWidget)
        self.basecallerBackgroundSubtractSlider.setMaximum(20)
        self.basecallerBackgroundSubtractSlider.setPageStep(5)
        self.basecallerBackgroundSubtractSlider.setProperty("value", QtCore.QVariant(5))
        self.basecallerBackgroundSubtractSlider.setSliderPosition(5)
        self.basecallerBackgroundSubtractSlider.setOrientation(QtCore.Qt.Horizontal)
        self.basecallerBackgroundSubtractSlider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.basecallerBackgroundSubtractSlider.setTickInterval(1)
        self.basecallerBackgroundSubtractSlider.setObjectName("basecallerBackgroundSubtractSlider")
        self.verticalLayout_20.addWidget(self.basecallerBackgroundSubtractSlider)
        spacerItem16 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_20.addItem(spacerItem16)
        self.basecallerRunBasecallerButton = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.basecallerRunBasecallerButton.setObjectName("basecallerRunBasecallerButton")
        self.verticalLayout_20.addWidget(self.basecallerRunBasecallerButton)
        self.horizontalLayout.addLayout(self.verticalLayout_20)
        self.basecallerOutputWindow = QtGui.QTextEdit(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.basecallerOutputWindow.sizePolicy().hasHeightForWidth())
        self.basecallerOutputWindow.setSizePolicy(sizePolicy)
        self.basecallerOutputWindow.setMinimumSize(QtCore.QSize(741, 0))
        self.basecallerOutputWindow.setObjectName("basecallerOutputWindow")
        self.horizontalLayout.addWidget(self.basecallerOutputWindow)
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_8 = QtGui.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.frame_8 = QtGui.QFrame(self.tab_8)
        self.frame_8.setGeometry(QtCore.QRect(10, 10, 381, 151))
        self.frame_8.setFrameShape(QtGui.QFrame.Box)
        self.frame_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayoutWidget_3 = QtGui.QWidget(self.frame_8)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 361, 131))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_77 = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label_77.setObjectName("label_77")
        self.verticalLayout_7.addWidget(self.label_77)
        self.aboutVersion = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.aboutVersion.setObjectName("aboutVersion")
        self.verticalLayout_7.addWidget(self.aboutVersion)
        self.aboutDate = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.aboutDate.setObjectName("aboutDate")
        self.verticalLayout_7.addWidget(self.aboutDate)
        self.label_35 = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label_35.setObjectName("label_35")
        self.verticalLayout_7.addWidget(self.label_35)
        self.label_36 = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label_36.setObjectName("label_36")
        self.verticalLayout_7.addWidget(self.label_36)
        self.tabWidget.addTab(self.tab_8, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.rawFlowcell.setCurrentIndex(2)
        self.histogramFileList.setCurrentRow(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.polonator_kill, self.pushButton)
        MainWindow.setTabOrder(self.pushButton, self.cycleListComplete)
        MainWindow.setTabOrder(self.cycleListComplete, self.cycleListPending)
        MainWindow.setTabOrder(self.cycleListPending, self.cycleListInProgress)
        MainWindow.setTabOrder(self.cycleListInProgress, self.startQC)
        MainWindow.setTabOrder(self.startQC, self.plainTextEdit)
        MainWindow.setTabOrder(self.plainTextEdit, self.imageJPanel2)
        MainWindow.setTabOrder(self.imageJPanel2, self.objectFC)
        MainWindow.setTabOrder(self.objectFC, self.objectLane)
        MainWindow.setTabOrder(self.objectLane, self.objectPosition)
        MainWindow.setTabOrder(self.objectPosition, self.objectDisplay)
        MainWindow.setTabOrder(self.objectDisplay, self.rawFlowcell)
        MainWindow.setTabOrder(self.rawFlowcell, self.rawLane)
        MainWindow.setTabOrder(self.rawLane, self.rawImage)
        MainWindow.setTabOrder(self.rawImage, self.histogramFlowcell)
        MainWindow.setTabOrder(self.histogramFlowcell, self.histogramLane)
        MainWindow.setTabOrder(self.histogramLane, self.histogramThreshold)
        MainWindow.setTabOrder(self.histogramThreshold, self.histogramDrawHistogram)
        MainWindow.setTabOrder(self.histogramDrawHistogram, self.histogramCutoff0_0)
        MainWindow.setTabOrder(self.histogramCutoff0_0, self.histogramCutoff0_1)
        MainWindow.setTabOrder(self.histogramCutoff0_1, self.histogramCutoff0_2)
        MainWindow.setTabOrder(self.histogramCutoff0_2, self.histogramCutoff0_3)
        MainWindow.setTabOrder(self.histogramCutoff0_3, self.histogramCutoff0_4)
        MainWindow.setTabOrder(self.histogramCutoff0_4, self.histogramCutoff0_5)
        MainWindow.setTabOrder(self.histogramCutoff0_5, self.histogramCutoff0_6)
        MainWindow.setTabOrder(self.histogramCutoff0_6, self.histogramCutoff0_7)
        MainWindow.setTabOrder(self.histogramCutoff0_7, self.histogramCutoff1_0)
        MainWindow.setTabOrder(self.histogramCutoff1_0, self.histogramCutoff1_1)
        MainWindow.setTabOrder(self.histogramCutoff1_1, self.histogramCutoff1_2)
        MainWindow.setTabOrder(self.histogramCutoff1_2, self.histogramCutoff1_3)
        MainWindow.setTabOrder(self.histogramCutoff1_3, self.histogramCutoff1_4)
        MainWindow.setTabOrder(self.histogramCutoff1_4, self.histogramCutoff1_5)
        MainWindow.setTabOrder(self.histogramCutoff1_5, self.histogramCutoff1_6)
        MainWindow.setTabOrder(self.histogramCutoff1_6, self.histogramCutoff1_7)
        MainWindow.setTabOrder(self.histogramCutoff1_7, self.histogramImportCutoffs)
        MainWindow.setTabOrder(self.histogramImportCutoffs, self.histogramExportCutoffs)
        MainWindow.setTabOrder(self.histogramExportCutoffs, self.histogramGenerateData)
        MainWindow.setTabOrder(self.histogramGenerateData, self.histogramSingleButton)
        MainWindow.setTabOrder(self.histogramSingleButton, self.histogramCycleButton)
        MainWindow.setTabOrder(self.histogramCycleButton, self.histogramOutputWindow)
        MainWindow.setTabOrder(self.histogramOutputWindow, self.basecallerAddButton)
        MainWindow.setTabOrder(self.basecallerAddButton, self.basecallerRemoveButton)
        MainWindow.setTabOrder(self.basecallerRemoveButton, self.basecallerAddAllButton)
        MainWindow.setTabOrder(self.basecallerAddAllButton, self.basecallerReadOrderList)
        MainWindow.setTabOrder(self.basecallerReadOrderList, self.basecallerDataKeepSlider)
        MainWindow.setTabOrder(self.basecallerDataKeepSlider, self.basecallerBackgroundSubtractSlider)
        MainWindow.setTabOrder(self.basecallerBackgroundSubtractSlider, self.basecallerRunBasecallerButton)
        MainWindow.setTabOrder(self.basecallerRunBasecallerButton, self.basecallerOutputWindow)
        MainWindow.setTabOrder(self.basecallerOutputWindow, self.pushButton_4)
        MainWindow.setTabOrder(self.pushButton_4, self.imageJPanel1)
        MainWindow.setTabOrder(self.imageJPanel1, self.alignXImageJPanel)
        MainWindow.setTabOrder(self.alignXImageJPanel, self.alignYImageJPanel)
        MainWindow.setTabOrder(self.alignYImageJPanel, self.rawRed)
        MainWindow.setTabOrder(self.rawRed, self.rawGreen)
        MainWindow.setTabOrder(self.rawGreen, self.rawBlue)
        MainWindow.setTabOrder(self.rawBlue, self.pushButton_3)
        MainWindow.setTabOrder(self.pushButton_3, self.pushButton_2)
        MainWindow.setTabOrder(self.pushButton_2, self.basecallerAvailCyclesList)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "updateProcesses", None, QtGui.QApplication.UnicodeUTF8))
        self.polonator_textarea.setStatusTip(QtGui.QApplication.translate("MainWindow", "Output window", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "CURRENT EXPERIMENT:", None, QtGui.QApplication.UnicodeUTF8))
        self.polonator_experiment.setStatusTip(QtGui.QApplication.translate("MainWindow", "Current experiment", None, QtGui.QApplication.UnicodeUTF8))
        self.polonator_initialize.setStatusTip(QtGui.QApplication.translate("MainWindow", "Initialize processor", None, QtGui.QApplication.UnicodeUTF8))
        self.polonator_initialize.setText(QtGui.QApplication.translate("MainWindow", "Initialize", None, QtGui.QApplication.UnicodeUTF8))
        self.polonator_process.setStatusTip(QtGui.QApplication.translate("MainWindow", "Process images", None, QtGui.QApplication.UnicodeUTF8))
        self.polonator_process.setText(QtGui.QApplication.translate("MainWindow", "Process images", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "CURRENT STATUS:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Image processing is:", None, QtGui.QApplication.UnicodeUTF8))
        self.polonator_processorstatus.setStatusTip(QtGui.QApplication.translate("MainWindow", "Image processor status", None, QtGui.QApplication.UnicodeUTF8))
        self.polonator_processorstatus.setText(QtGui.QApplication.translate("MainWindow", "NOT RUNNING", None, QtGui.QApplication.UnicodeUTF8))
        self.polonator_processorpath.setStatusTip(QtGui.QApplication.translate("MainWindow", "Image processor path", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Pipeline initialization is:", None, QtGui.QApplication.UnicodeUTF8))
        self.polonator_initializestatus.setStatusTip(QtGui.QApplication.translate("MainWindow", "Initializer status", None, QtGui.QApplication.UnicodeUTF8))
        self.polonator_initializestatus.setText(QtGui.QApplication.translate("MainWindow", "NOT RUNNING", None, QtGui.QApplication.UnicodeUTF8))
        self.polonator_initializepath.setStatusTip(QtGui.QApplication.translate("MainWindow", "Pipeline initialization path", None, QtGui.QApplication.UnicodeUTF8))
        self.polonator_kill.setStatusTip(QtGui.QApplication.translate("MainWindow", "Kill software and update processor", None, QtGui.QApplication.UnicodeUTF8))
        self.polonator_kill.setText(QtGui.QApplication.translate("MainWindow", "STOP ALL PROCESSING SOFTWARE", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), QtGui.QApplication.translate("MainWindow", "Polonator", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_4.setText(QtGui.QApplication.translate("MainWindow", "updateQualityLists", None, QtGui.QApplication.UnicodeUTF8))
        self.cycleListComplete.setStatusTip(QtGui.QApplication.translate("MainWindow", "Complete cycles", None, QtGui.QApplication.UnicodeUTF8))
        self.cycleListPending.setStatusTip(QtGui.QApplication.translate("MainWindow", "Pending cycles", None, QtGui.QApplication.UnicodeUTF8))
        self.cycleListInProgress.setStatusTip(QtGui.QApplication.translate("MainWindow", "Cycles in progress", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Complete Cycles", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Pending Cycles", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "In Progress", None, QtGui.QApplication.UnicodeUTF8))
        self.startQC.setStatusTip(QtGui.QApplication.translate("MainWindow", "Start QC", None, QtGui.QApplication.UnicodeUTF8))
        self.startQC.setText(QtGui.QApplication.translate("MainWindow", "QC", None, QtGui.QApplication.UnicodeUTF8))
        self.imageJPanel1.setStatusTip(QtGui.QApplication.translate("MainWindow", "fchist image", None, QtGui.QApplication.UnicodeUTF8))
        self.imageJPanel2.setStatusTip(QtGui.QApplication.translate("MainWindow", "fcmap image", None, QtGui.QApplication.UnicodeUTF8))
        self.alignXImageJPanel.setStatusTip(QtGui.QApplication.translate("MainWindow", "fcregX image", None, QtGui.QApplication.UnicodeUTF8))
        self.alignYImageJPanel.setStatusTip(QtGui.QApplication.translate("MainWindow", "fcregY image", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Cycle Quality", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Flowcell", None, QtGui.QApplication.UnicodeUTF8))
        self.objectFC.setStatusTip(QtGui.QApplication.translate("MainWindow", "Flowcell", None, QtGui.QApplication.UnicodeUTF8))
        self.objectFC.setItemText(0, QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.objectFC.setItemText(1, QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Lane", None, QtGui.QApplication.UnicodeUTF8))
        self.objectLane.setStatusTip(QtGui.QApplication.translate("MainWindow", "Lane in flowcell", None, QtGui.QApplication.UnicodeUTF8))
        self.objectLane.setItemText(0, QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.objectLane.setItemText(1, QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.objectLane.setItemText(2, QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.objectLane.setItemText(3, QtGui.QApplication.translate("MainWindow", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.objectLane.setItemText(4, QtGui.QApplication.translate("MainWindow", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.objectLane.setItemText(5, QtGui.QApplication.translate("MainWindow", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.objectLane.setItemText(6, QtGui.QApplication.translate("MainWindow", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.objectLane.setItemText(7, QtGui.QApplication.translate("MainWindow", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Position", None, QtGui.QApplication.UnicodeUTF8))
        self.objectPosition.setStatusTip(QtGui.QApplication.translate("MainWindow", "Position in flowcell lane", None, QtGui.QApplication.UnicodeUTF8))
        self.objectDisplay.setStatusTip(QtGui.QApplication.translate("MainWindow", "Display objects in the specified flowcell, lane, and position", None, QtGui.QApplication.UnicodeUTF8))
        self.objectDisplay.setText(QtGui.QApplication.translate("MainWindow", "Display objects", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("MainWindow", "Object Finder", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Flowcell", None, QtGui.QApplication.UnicodeUTF8))
        self.rawFlowcell.setStatusTip(QtGui.QApplication.translate("MainWindow", "Flowcell", None, QtGui.QApplication.UnicodeUTF8))
        self.rawFlowcell.setItemText(0, QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.rawFlowcell.setItemText(1, QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Lane", None, QtGui.QApplication.UnicodeUTF8))
        self.rawLane.setStatusTip(QtGui.QApplication.translate("MainWindow", "Lane in flowcell", None, QtGui.QApplication.UnicodeUTF8))
        self.rawLane.setItemText(0, QtGui.QApplication.translate("MainWindow", "00", None, QtGui.QApplication.UnicodeUTF8))
        self.rawLane.setItemText(1, QtGui.QApplication.translate("MainWindow", "01", None, QtGui.QApplication.UnicodeUTF8))
        self.rawLane.setItemText(2, QtGui.QApplication.translate("MainWindow", "02", None, QtGui.QApplication.UnicodeUTF8))
        self.rawLane.setItemText(3, QtGui.QApplication.translate("MainWindow", "03", None, QtGui.QApplication.UnicodeUTF8))
        self.rawLane.setItemText(4, QtGui.QApplication.translate("MainWindow", "04", None, QtGui.QApplication.UnicodeUTF8))
        self.rawLane.setItemText(5, QtGui.QApplication.translate("MainWindow", "05", None, QtGui.QApplication.UnicodeUTF8))
        self.rawLane.setItemText(6, QtGui.QApplication.translate("MainWindow", "06", None, QtGui.QApplication.UnicodeUTF8))
        self.rawLane.setItemText(7, QtGui.QApplication.translate("MainWindow", "07", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "Image", None, QtGui.QApplication.UnicodeUTF8))
        self.rawImage.setStatusTip(QtGui.QApplication.translate("MainWindow", "Image in flowcell lane", None, QtGui.QApplication.UnicodeUTF8))
        self.rawCycleList.setStatusTip(QtGui.QApplication.translate("MainWindow", "Cycle list", None, QtGui.QApplication.UnicodeUTF8))
        self.label_37.setText(QtGui.QApplication.translate("MainWindow", "Cycle List", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "Red", None, QtGui.QApplication.UnicodeUTF8))
        self.rawRed.setStatusTip(QtGui.QApplication.translate("MainWindow", "Red A, C, T, G, or none", None, QtGui.QApplication.UnicodeUTF8))
        self.rawRed.setItemText(0, QtGui.QApplication.translate("MainWindow", "A", None, QtGui.QApplication.UnicodeUTF8))
        self.rawRed.setItemText(1, QtGui.QApplication.translate("MainWindow", "C", None, QtGui.QApplication.UnicodeUTF8))
        self.rawRed.setItemText(2, QtGui.QApplication.translate("MainWindow", "G", None, QtGui.QApplication.UnicodeUTF8))
        self.rawRed.setItemText(3, QtGui.QApplication.translate("MainWindow", "T", None, QtGui.QApplication.UnicodeUTF8))
        self.rawRed.setItemText(4, QtGui.QApplication.translate("MainWindow", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "Green", None, QtGui.QApplication.UnicodeUTF8))
        self.rawGreen.setStatusTip(QtGui.QApplication.translate("MainWindow", "Green A, C, T, G, or none", None, QtGui.QApplication.UnicodeUTF8))
        self.rawGreen.setItemText(0, QtGui.QApplication.translate("MainWindow", "A", None, QtGui.QApplication.UnicodeUTF8))
        self.rawGreen.setItemText(1, QtGui.QApplication.translate("MainWindow", "C", None, QtGui.QApplication.UnicodeUTF8))
        self.rawGreen.setItemText(2, QtGui.QApplication.translate("MainWindow", "G", None, QtGui.QApplication.UnicodeUTF8))
        self.rawGreen.setItemText(3, QtGui.QApplication.translate("MainWindow", "T", None, QtGui.QApplication.UnicodeUTF8))
        self.rawGreen.setItemText(4, QtGui.QApplication.translate("MainWindow", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "Blue", None, QtGui.QApplication.UnicodeUTF8))
        self.rawBlue.setStatusTip(QtGui.QApplication.translate("MainWindow", "Blue A, C, T, G, or none", None, QtGui.QApplication.UnicodeUTF8))
        self.rawBlue.setItemText(0, QtGui.QApplication.translate("MainWindow", "A", None, QtGui.QApplication.UnicodeUTF8))
        self.rawBlue.setItemText(1, QtGui.QApplication.translate("MainWindow", "C", None, QtGui.QApplication.UnicodeUTF8))
        self.rawBlue.setItemText(2, QtGui.QApplication.translate("MainWindow", "G", None, QtGui.QApplication.UnicodeUTF8))
        self.rawBlue.setItemText(3, QtGui.QApplication.translate("MainWindow", "T", None, QtGui.QApplication.UnicodeUTF8))
        self.rawBlue.setItemText(4, QtGui.QApplication.translate("MainWindow", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.rawDisplay.setStatusTip(QtGui.QApplication.translate("MainWindow", "Display color overlay", None, QtGui.QApplication.UnicodeUTF8))
        self.rawDisplay.setText(QtGui.QApplication.translate("MainWindow", "Display color overlay", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QtGui.QApplication.translate("MainWindow", "Raw Images", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setText(QtGui.QApplication.translate("MainWindow", "initializeHistogramCutoffFields", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("MainWindow", "Histogram File List", None, QtGui.QApplication.UnicodeUTF8))
        self.histogramFileList.setStatusTip(QtGui.QApplication.translate("MainWindow", "Histogram file list", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "Flowcell", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", "Lane", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("MainWindow", "Threshold", None, QtGui.QApplication.UnicodeUTF8))
        self.histogramThreshold.setStatusTip(QtGui.QApplication.translate("MainWindow", "Threshold", None, QtGui.QApplication.UnicodeUTF8))
        self.histogramThreshold.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.histogramLane.setStatusTip(QtGui.QApplication.translate("MainWindow", "Lane in flowcell", None, QtGui.QApplication.UnicodeUTF8))
        self.histogramLane.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.histogramFlowcell.setStatusTip(QtGui.QApplication.translate("MainWindow", "Flowcell", None, QtGui.QApplication.UnicodeUTF8))
        self.histogramFlowcell.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.histogramDrawHistogram.setStatusTip(QtGui.QApplication.translate("MainWindow", "Display histogram", None, QtGui.QApplication.UnicodeUTF8))
        self.histogramDrawHistogram.setText(QtGui.QApplication.translate("MainWindow", "Display histogram", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("MainWindow", "Basecalling Cutoffs", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("MainWindow", "Flowcell 0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("MainWindow", "Lane 0", None, QtGui.QApplication.UnicodeUTF8))
        self.histogramCutoff0_0.setStatusTip(QtGui.QApplication.translate("MainWindow", "Lane 0 cutoff", None, QtGui.QApplication.UnicodeUTF8))
        self.histogramCutoff0_0.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setText(QtGui.QApplication.translate("MainWindow", "Lane 1", None, QtGui.QApplication.UnicodeUTF8))
        self.histogramCutoff0_1.setStatusTip(QtGui.QApplication.translate("MainWindow", "Lane 1 cutoff", None, QtGui.QApplication.UnicodeUTF8))
        self.histogramCutoff0_1.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("MainWindow", "Lane 2", None, QtGui.QApplication.UnicodeUTF8))
        self.histogramCutoff0_2.setStatusTip(QtGui.QApplication.translate("MainWindow", "Lane 2 cutoff", None, QtGui.QApplication.UnicodeUTF8))
        self.histogramCutoff0_2.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("MainWindow", "Lane 3", None, QtGui.QApplication.UnicodeUTF8))
        self.histogramCutoff0_3.setStatusTip(QtGui.QApplication.translate("MainWindow", "Lane 3 cutoff", None, QtGui.QApplication.UnicodeUTF8))
        self.histogramCutoff0_3.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("MainWindow", "Lane 4", None, QtGui.QApplication.UnicodeUTF8))
        self.histogramCutoff0_4.setStatusTip(QtGui.QApplication.translate("MainWindow", "Lane 4 cutoff", None, QtGui.QApplication.UnicodeUTF8))
        self.histogramCutoff0_4.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("MainWindow", "Lane 5", None, QtGui.QApplication.UnicodeUTF8))
        self.histogramCutoff0_5.setStatusTip(QtGui.QApplication.translate("MainWindow", "Lane 5 cutoff", None, QtGui.QApplication.UnicodeUTF8))
        self.histogramCutoff0_5.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("MainWindow", "Lane 6", None, QtGui.QApplication.UnicodeUTF8))
        self.histogramCutoff0_6.setStatusTip(QtGui.QApplication.translate("MainWindow", "Lane 6 cutoff", None, QtGui.QApplication.UnicodeUTF8))
        self.histogramCutoff0_6.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("MainWindow", "Lane 7", None, QtGui.QApplication.UnicodeUTF8))
        self.histogramCutoff0_7.setStatusTip(QtGui.QApplication.translate("MainWindow", "Lane 7 cutoff", None, QtGui.QApplication.UnicodeUTF8))
        self.histogramCutoff0_7.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_67.setText(QtGui.QApplication.translate("MainWindow", "Flowcell 1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_68.setText(QtGui.QApplication.translate("MainWindow", "Lane 0", None, QtGui.QApplication.UnicodeUTF8))
        self.histogramCutoff1_0.setStatusTip(QtGui.QApplication.translate("MainWindow", "Lane 0 cutoff", None, QtGui.QApplication.UnicodeUTF8))
        self.histogramCutoff1_0.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_69.setText(QtGui.QApplication.translate("MainWindow", "Lane 1", None, QtGui.QApplication.UnicodeUTF8))
        self.histogramCutoff1_1.setStatusTip(QtGui.QApplication.translate("MainWindow", "Lane 1 cutoff", None, QtGui.QApplication.UnicodeUTF8))
        self.histogramCutoff1_1.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_70.setText(QtGui.QApplication.translate("MainWindow", "Lane 2", None, QtGui.QApplication.UnicodeUTF8))
        self.histogramCutoff1_2.setStatusTip(QtGui.QApplication.translate("MainWindow", "Lane 2 cutoff", None, QtGui.QApplication.UnicodeUTF8))
        self.histogramCutoff1_2.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_71.setText(QtGui.QApplication.translate("MainWindow", "Lane 3", None, QtGui.QApplication.UnicodeUTF8))
        self.histogramCutoff1_3.setStatusTip(QtGui.QApplication.translate("MainWindow", "Lane 3 cutoff", None, QtGui.QApplication.UnicodeUTF8))
        self.histogramCutoff1_3.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_72.setText(QtGui.QApplication.translate("MainWindow", "Lane 4", None, QtGui.QApplication.UnicodeUTF8))
        self.histogramCutoff1_4.setStatusTip(QtGui.QApplication.translate("MainWindow", "Lane 4 cutoff", None, QtGui.QApplication.UnicodeUTF8))
        self.histogramCutoff1_4.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_73.setText(QtGui.QApplication.translate("MainWindow", "Lane 5", None, QtGui.QApplication.UnicodeUTF8))
        self.histogramCutoff1_5.setStatusTip(QtGui.QApplication.translate("MainWindow", "Lane 5 cutoff", None, QtGui.QApplication.UnicodeUTF8))
        self.histogramCutoff1_5.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_74.setText(QtGui.QApplication.translate("MainWindow", "Lane 6", None, QtGui.QApplication.UnicodeUTF8))
        self.histogramCutoff1_6.setStatusTip(QtGui.QApplication.translate("MainWindow", "Lane 6 cutoff", None, QtGui.QApplication.UnicodeUTF8))
        self.histogramCutoff1_6.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_75.setText(QtGui.QApplication.translate("MainWindow", "Lane 7", None, QtGui.QApplication.UnicodeUTF8))
        self.histogramCutoff1_7.setStatusTip(QtGui.QApplication.translate("MainWindow", "Lane 7 cutoff", None, QtGui.QApplication.UnicodeUTF8))
        self.histogramCutoff1_7.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.histogramImportCutoffs.setStatusTip(QtGui.QApplication.translate("MainWindow", "Import cutoffs from file", None, QtGui.QApplication.UnicodeUTF8))
        self.histogramImportCutoffs.setText(QtGui.QApplication.translate("MainWindow", "IMPORT CUTOFFS", None, QtGui.QApplication.UnicodeUTF8))
        self.histogramExportCutoffs.setStatusTip(QtGui.QApplication.translate("MainWindow", "Export cutoffs to file", None, QtGui.QApplication.UnicodeUTF8))
        self.histogramExportCutoffs.setText(QtGui.QApplication.translate("MainWindow", "EXPORT CUTOFFS", None, QtGui.QApplication.UnicodeUTF8))
        self.histogramGenerateData.setStatusTip(QtGui.QApplication.translate("MainWindow", "Generate cycle data", None, QtGui.QApplication.UnicodeUTF8))
        self.histogramGenerateData.setText(QtGui.QApplication.translate("MainWindow", "GENERATE DATA", None, QtGui.QApplication.UnicodeUTF8))
        self.histogramSingleButton.setStatusTip(QtGui.QApplication.translate("MainWindow", "Single", None, QtGui.QApplication.UnicodeUTF8))
        self.histogramSingleButton.setText(QtGui.QApplication.translate("MainWindow", "Single", None, QtGui.QApplication.UnicodeUTF8))
        self.histogramCycleButton.setStatusTip(QtGui.QApplication.translate("MainWindow", "Cycle", None, QtGui.QApplication.UnicodeUTF8))
        self.histogramCycleButton.setText(QtGui.QApplication.translate("MainWindow", "Cycle", None, QtGui.QApplication.UnicodeUTF8))
        self.histogramOutputWindow.setStatusTip(QtGui.QApplication.translate("MainWindow", "Histogram output", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), QtGui.QApplication.translate("MainWindow", "Histogram", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("MainWindow", "update_basecaller AvailableList", None, QtGui.QApplication.UnicodeUTF8))
        self.basecallerAvailCyclesList.setStatusTip(QtGui.QApplication.translate("MainWindow", "Available cycles", None, QtGui.QApplication.UnicodeUTF8))
        self.basecallerReadOrderList.setStatusTip(QtGui.QApplication.translate("MainWindow", "Cycle read order", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("MainWindow", "Available cycles", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("MainWindow", "Read order", None, QtGui.QApplication.UnicodeUTF8))
        self.basecallerAddButton.setStatusTip(QtGui.QApplication.translate("MainWindow", "Add cycle to read list", None, QtGui.QApplication.UnicodeUTF8))
        self.basecallerAddButton.setText(QtGui.QApplication.translate("MainWindow", "ADD -->", None, QtGui.QApplication.UnicodeUTF8))
        self.basecallerRemoveButton.setStatusTip(QtGui.QApplication.translate("MainWindow", "Remove cycle from read list", None, QtGui.QApplication.UnicodeUTF8))
        self.basecallerRemoveButton.setText(QtGui.QApplication.translate("MainWindow", "<-- REMOVE", None, QtGui.QApplication.UnicodeUTF8))
        self.basecallerAddAllButton.setStatusTip(QtGui.QApplication.translate("MainWindow", "Add all cycles to read list", None, QtGui.QApplication.UnicodeUTF8))
        self.basecallerAddAllButton.setText(QtGui.QApplication.translate("MainWindow", "ADD ALL -->", None, QtGui.QApplication.UnicodeUTF8))
        self.basecallerUpButton.setStatusTip(QtGui.QApplication.translate("MainWindow", "Move selected cycle up the read order", None, QtGui.QApplication.UnicodeUTF8))
        self.basecallerUpButton.setText(QtGui.QApplication.translate("MainWindow", "Up", None, QtGui.QApplication.UnicodeUTF8))
        self.basecallerDownButton.setStatusTip(QtGui.QApplication.translate("MainWindow", "Move selected cycle down the read order", None, QtGui.QApplication.UnicodeUTF8))
        self.basecallerDownButton.setText(QtGui.QApplication.translate("MainWindow", "Down", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("MainWindow", "Base name of readfile", None, QtGui.QApplication.UnicodeUTF8))
        self.basecallerReadfileFN.setStatusTip(QtGui.QApplication.translate("MainWindow", "Base name of readfile", None, QtGui.QApplication.UnicodeUTF8))
        self.basecallerReadfileFN.setText(QtGui.QApplication.translate("MainWindow", "Default", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("MainWindow", "Percentage of data to keep:", None, QtGui.QApplication.UnicodeUTF8))
        self.basecallerPercentToKeepLabel.setText(QtGui.QApplication.translate("MainWindow", "50", None, QtGui.QApplication.UnicodeUTF8))
        self.basecallerDataKeepSlider.setStatusTip(QtGui.QApplication.translate("MainWindow", "Percentage of data to keep", None, QtGui.QApplication.UnicodeUTF8))
        self.label_76.setText(QtGui.QApplication.translate("MainWindow", "Percent background subtract:", None, QtGui.QApplication.UnicodeUTF8))
        self.basecallerPercentBGSubtractLabel.setText(QtGui.QApplication.translate("MainWindow", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.basecallerBackgroundSubtractSlider.setStatusTip(QtGui.QApplication.translate("MainWindow", "Percent of background to be subtracted", None, QtGui.QApplication.UnicodeUTF8))
        self.basecallerRunBasecallerButton.setStatusTip(QtGui.QApplication.translate("MainWindow", "Run basecaller", None, QtGui.QApplication.UnicodeUTF8))
        self.basecallerRunBasecallerButton.setText(QtGui.QApplication.translate("MainWindow", "RUN BASECALLER", None, QtGui.QApplication.UnicodeUTF8))
        self.basecallerOutputWindow.setStatusTip(QtGui.QApplication.translate("MainWindow", "Basecaller output", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), QtGui.QApplication.translate("MainWindow", "Basecaller", None, QtGui.QApplication.UnicodeUTF8))
        self.label_77.setText(QtGui.QApplication.translate("MainWindow", "Polonator Data Processing Control Interface", None, QtGui.QApplication.UnicodeUTF8))
        self.label_35.setText(QtGui.QApplication.translate("MainWindow", "Written by David Kalish", None, QtGui.QApplication.UnicodeUTF8))
        self.label_36.setText(QtGui.QApplication.translate("MainWindow", "Wyss Institute, Harvard Medical, Boston, MA", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "Cycle Alignment", None, QtGui.QApplication.UnicodeUTF8))

